### ISSUE TITLE
Oceanic Tracks (Atlantic and Pacific)

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Navigation#100]
Being worked on :)

**Comment by Swang007** [comment]
@DavidCutler: Henrik & I finished westbound & eastbound tracks today

**Comment by DavidCutler** [comment]
@Swang007 @henrikbg Roger that! Are you guys available now? We could knock out the Pacific tonight..?

**Comment by henrikbg** [comment]
I'm available in 15.

**Comment by Swang007** [comment]
Anything else we need to do?

**Comment by henrikbg** [comment]
Nope, we're done.
