### ISSUE TITLE
UWPS

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#1007]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS (runway created).

# Runway(s) with ILS: (If any)

Runway 20.

# References: (Official sources/charts)
 
![image](https://user-images.githubusercontent.com/22130457/42401550-bb0ffaf2-813b-11e8-946c-2eff20608787.png)

![image](https://user-images.githubusercontent.com/22130457/42401558-c02bea32-813b-11e8-9eb4-a25f6e9e19c0.png)

**Comment by AleksanderIF** [comment]
sorry for duplicating issue, ILS added in #1643
