### ISSUE TITLE
EDJA - Memmingen: Runway 24/06 moved

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#101]
I moved Runway 24 (equipped with ILS) a bit to allign it with the WEDbing scenery

**Comment by henrikbg** [comment]
@moritzbabl, has this been committed to the repo?

**Comment by moritzbabl** [comment]
Not yet, I'll send the email in a few minutes

**Comment by henrikbg** [comment]
Done.
