### ISSUE TITLE
KBWI

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#1016]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runways moved (redone from scratch). 

# Runway(s) with ILS: (If any)

10/28, 15R/33L, 15L/33R (all).

# References: (Official sources/charts)

https://flightaware.com/resources/airport/BWI/IAP/ILS+OR+LOC+RWY+10
https://flightaware.com/resources/airport/BWI/IAP/ILS+OR+LOC+RWY+28
https://flightaware.com/resources/airport/KBWI/IAP/ILS+OR+LOC+RWY+15L
https://flightaware.com/resources/airport/BWI/IAP/ILS+OR+LOC+RWY+15R
https://flightaware.com/resources/airport/BWI/IAP/ILS+OR+LOC+RWY+33L
https://flightaware.com/resources/airport/BWI/IAP/ILS+OR+LOC+RWY+33R

**Comment by brennanhackard** [comment]
I'll fix this.

**Comment by brennanhackard** [comment]
Fixed in #1504
