### ISSUE TITLE
RJOI

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Navigation#1022]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

massive reconstruction of airfield in real world. Runway moved several 100ft East. 

# Runway(s) with ILS: (If any)

RWY02

# References: (Official sources/charts)

https://aisjapan.mlit.go.jp/Login.do
[JP-AD-2-RJOI-en-JP.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/2211530/JP-AD-2-RJOI-en-JP.pdf)
[JP-AD-2.24.1-RJOI-en-JP.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/2211531/JP-AD-2.24.1-RJOI-en-JP.pdf)

**Comment by CptNathanHope** [comment]
Fixed by @orangejuicie
