### ISSUE TITLE
ZURK

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1028]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Airport added to folder

# Runway(s) with ILS: (If any)

09/27

# References: (Official sources/charts)

https://en.wikipedia.org/wiki/Shigatse_Peace_Airport

**Comment by MajorTomMueller** [comment]
No AIP available, no evidence of ILS in Google Earth. 
Linked "Reference" is not, and contains no link to, official source or chart
Issue to recycle
