### ISSUE TITLE
RKSO

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#1033]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway added

# Runway(s) with ILS: (If any)

09L,27R

# References: (Official sources/charts)

http://www.ut.ac.kr/cmm/fms/FileDown.do;jsessionid=F40rEV2kMe2yMLa2aeLPmqd2xnEECA3J1HRH8JRkqPX5THuZMml8yn8YHwzwk9MY.homepage_servlet_engine1?atchFileId=FILE_000000000106643&fileSn=2

**Comment by MajorTomMueller** [comment]
Hi @ItsW1ll ,
sorry, haven't noticed that you were assigned to this issue already. Just made a pull-request about it....

**Comment by ItsW1ll** [comment]
That’s alright will update the issue
