### ISSUE TITLE
SBBH

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1044]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Airport redone from scratch >

# Runway(s) with ILS: (If any)

< LOC on runway 13 >

# References: (Official sources/charts)

< http://ais.decea.gov.br/download/?arquivo=6332593e-ae8c-1033-a49b-72567f175e3a&apikey=1587263166 >

**Comment by Czechoslovaki** [comment]
#1620

**Comment by zhf21** [comment]
ILS-Cat-I -> LOC.

<img width="402" alt="Screen Shot 2021-09-27 at 8 09 08 PM" src="https://user-images.githubusercontent.com/67797012/135001601-8313fdb7-63d6-40e4-91a7-2d87ca437853.png">
