### ISSUE TITLE
LATI

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1048]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway 

# Runway(s) with ILS: (If any)
17

# References: (Official sources/charts)

http://albcontrol.al/al/aip/19-Jul-2018-A/2018-07-19-AIRAC/html/eAIP/LA-AD-2.LATI-en-GB.html#LATI2009072112063219

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by ECoops-123** [comment]
Runway moved. Will fix.
