### ISSUE TITLE
ROAH

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1051]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

36

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by zhf21** [comment]
Hi. Me here. I'll be fixing/adding the ILSes for this airport. 

**RWY 18R:** https://github.com/InfiniteFlightAirportEditing/Navigation/files/6563811/ROAH_ILS_or_LOC_RWY18R.pdf
**RWY 36L:** https://github.com/InfiniteFlightAirportEditing/Navigation/files/6563815/ROAH_ILS_or_LOC_RWY36L.pdf)
**RWY 36R:** https://github.com/InfiniteFlightAirportEditing/Navigation/files/6563814/ROAH_ILS_or_LOC_RWY36R.pdf

**Comment by zhf21** [comment]
All done!

Amazing job with this airport, @OscarConklin!
