### ISSUE TITLE
ENRA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1056]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

32

# References: (Official sources/charts)

Name: LOC, Identifier: RA with true heading 80.5° is 127° off of airport ENRA's runway 32 true heading of 318.5°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Airport doesn't have ILS

**Comment by Velocity23** [comment]
Working on this. Seems to be a duplicate LOC.
