### ISSUE TITLE
KASE

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1057]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

LOC RWY 15

# References: (Official sources/charts)

Name: LOC, Identifier: IPKN with true heading 312.0° is 152° off of airport KASE's runway 15 true heading of 159.5°

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Airport doesn't have ILS

**Comment by ItsW1ll** [comment]
Keep this one open. It seems to have a LOC
