### ISSUE TITLE
KOMA

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Navigation#1059]
14L/32R, 14R/32L, 18/36 ILS

https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+14L
https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+14R
https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+18
https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+32L
https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+32R
https://flightaware.com/resources/airport/KOMA/IAP/ILS+OR+LOC+RWY+36

**Comment by brennanhackard** [comment]
Fixed :D
