### ISSUE TITLE
UBBB

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1060]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

16,17,34,35

# References: (Official sources/charts)

Name: GS, Identifier: IBA with true heading 180.0° is 179° off of airport UBBB's runway 36 true heading of 359.4°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Working on this
