### ISSUE TITLE
LFSX

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1061]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

29 is misalinged

# References: (Official sources/charts)

Name: ILS-cat-I, Identifier: LXI with true heading 113.0° is 180° off of airport LFSX's runway 29 true heading of 293.2°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Working on this.
