### ISSUE TITLE
KLTS

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1062]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved, bearing is off

# Runway(s) with ILS: (If any)

17L/R 35LR
# References: (Official sources/charts)

Name: GS, Identifier: ILTS with true heading 180.0° is 180° off of airport KLTS's runway 35L true heading of 0.0°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Working on this
