### ISSUE TITLE
KRDR

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1063]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

05

# References: (Official sources/charts)

Name: GS, Identifier: IRDR with true heading 180.0° is 180° off of airport KRDR's runway 35 true heading of 0.0°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Working on this
