### ISSUE TITLE
CYBL

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1064]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway heading is wrong

# Runway(s) with ILS: (If any)

29

# References: (Official sources/charts)

Name: ILS-cat-I, Identifier: IBL with true heading 134.4° is 180° off of airport CYBL's runway 29 true heading of 315.2°.

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by Velocity23** [comment]
Working on this
