### ISSUE TITLE
EHGG

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1065]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved, glideslope out

# Runway(s) with ILS: (If any)

23 Only

# References: (Official sources/charts)

http://www.ais-netherlands.nl/aim/2018-12-20-AIRAC/html/eAIP/EH-AD-2.EHGG-en-GB.html#ehgg-ad-2.24

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by benjwri** [comment]
Fixed
