### ISSUE TITLE
EHRD

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1066]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved, glide slope appears to be out

# Runway(s) with ILS: (If any)

06/24

# References: (Official sources/charts)

http://www.ais-netherlands.nl/aim/2018-12-20-AIRAC/html/eAIP/EH-AD-2.EHRD-en-GB.html#ehrd-ad-2.24

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._

**Comment by MajorTomMueller** [comment]
Freq for LOC ROS on RWY04 is wrong

**Comment by MajorTomMueller** [comment]
solved in PR #1346
