### ISSUE TITLE
EHEH

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1067]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved, glideslope appears to be out.

# Runway(s) with ILS: (If any)

03/21

# References: (Official sources/charts)

http://www.ais-netherlands.nl/aim/2018-12-20-AIRAC/html/eAIP/EH-AD-2.EHEH-en-GB.html#eheh-ad-2.24

**Comment by CptNathanHope** [comment]
_Runway(s) not equipped with ILS or LOC._
