### ISSUE TITLE
SAWG

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1074]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Airport redone from scratch

# Runway(s) with ILS: (If any)

ILS runway 25

# References: (Official sources/charts)

http://www.todovuelo.com.ar/cartas/mapri%202012/RIO%20GALLEGOS%20-%20SAWG/sawg.pdf

**Comment by benjwri** [comment]
Fixed
