### ISSUE TITLE
SBVT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1075]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Airport redone from scratch.

# Runway(s) with ILS: (If any)

ILS RWY 24
Note: The numbering of runway 5/23 has changed to 6/24.

# References: (Official sources/charts)

http://ais.decea.gov.br/download/?arquivo=ea35d37e-62d6-4c66-a4cd0a5f04a714c0&apikey=1587263166

**Comment by benjwri** [comment]
Fixed
