### ISSUE TITLE
SBSN

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1076]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Airport redone from scratch

# Runway(s) with ILS: (If any)

ILS RWY 10

# References: (Official sources/charts)

http://ais.decea.gov.br/download/?arquivo=14ab76fa-3de8-1030-95e7-72567f175e3a&apikey=1587263166

**Comment by benjwri** [comment]
Fixed, ILS has been withdrawn

**Comment by zhf21** [comment]
ILS does not exist in the code. Will add.

<img width="1440" alt="Screen Shot 2021-09-28 at 2 04 04 PM" src="https://user-images.githubusercontent.com/67797012/135141265-c93ddd2c-53c1-469e-a660-d0df8052d52d.png">

<img width="408" alt="Screen Shot 2021-09-28 at 2 04 29 PM" src="https://user-images.githubusercontent.com/67797012/135141320-24f00734-f825-4442-a432-ef2b4816d51b.png">
