### ISSUE TITLE
SAVC

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1077]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

RWY 25

# References: (Official sources/charts)

http://ww1.jeppesen.com/documents/aviation/notices-alerts/chart-alert/SAVC/SAVCfiles.pdf

**Comment by benjwri** [comment]
Fixed
