### ISSUE TITLE
SBCJ

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1081]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

RWY 10

# References: (Official sources/charts)

http://ais.decea.gov.br/download/?arquivo=c5b9e324-3de7-1030-95e7-72567f175e3a&apikey=1587263166
http://ais.decea.gov.br/download/?arquivo=c5ba3356-3de7-1030-95e7-72567f175e3a&apikey=1587263166

**Comment by benjwri** [comment]
Fixed
