### ISSUE TITLE
KEWR

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#1091]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

4L/22R, 4R/22, 11

# References: (Official sources/charts)

https://www.flightaware.com/resources/airport/KEWR/IAP/ILS+OR+LOC+RWY+04L
https://www.flightaware.com/resources/airport/KEWR/IAP/ILS+OR+LOC+RWY+22R
https://www.flightaware.com/resources/airport/KEWR/IAP/ILS+OR+LOC+RWY+04R
https://www.flightaware.com/resources/airport/KEWR/IAP/ILS+OR+LOC+RWY+22L
https://www.flightaware.com/resources/airport/KEWR/IAP/ILS+OR+LOC+RWY+11

**Comment by ItsW1ll** [comment]
needs correction to just 4R

**Comment by CptNathanHope** [comment]
All fixed apparently.

**Comment by ItsW1ll** [comment]
Fixed in f74be65

**Comment by zhf21** [comment]
The ILSes will need some minor adjustments after @Czechoslovaki’s amazing updates to the airport. 

Specifically, Runway 22L’s ILS category needs to be changed, as well as the bearings for all runways.

I will take care of this.

**Comment by zhf21** [comment]
RWY 4L ILS CAT II - https://aeronav.faa.gov/d-tpp/2105/00285I4LSAC1_2.PDF
RWY 4R ILS CAT III - https://aeronav.faa.gov/d-tpp/2105/00285I4RC2_3.PDF
RWY 11 ILS CAT I - https://aeronav.faa.gov/d-tpp/2105/00285IL11.PDF
RWY 22L ILS CAT III - https://aeronav.faa.gov/d-tpp/2105/00285I22LC2_3.PDF
RWY 22R ILS CAT I - https://aeronav.faa.gov/d-tpp/2105/00285IL22R.PDF
