### ISSUE TITLE
KPDK

### ISSUE THREAD

**Issue by ChrisLevet232** [InfiniteFlightAirportEditing/Navigation#1101]
# Runway numbers have changed and ILS Runway 21L needs to be checked.

< Runway numbers changed from 20L/2R to 21L/3R and 20R/2L to 21R/3L>

# Runway(s) with ILS: (If any)

< 21L has ILS >

# References: (Official sources/charts)

< Jeppesen KPDK 50-9 dated 2 June 17 >

**Comment by benjwri** [comment]
Already fixed
