### ISSUE TITLE
KLVN

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Navigation#1112]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS - Airport Elevation Changed

# Runway(s) with ILS: (If any)

30

# References: (Official sources/charts)

< Enter text here >
[06652IL30.PDF](https://github.com/InfiniteFlightAirportEditing/Navigation/files/2536837/06652IL30.PDF)

**Comment by benjwri** [comment]
Fixed
