### ISSUE TITLE
OAKN

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Navigation#1114]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS, Runway moved to official treshold coordinates in Airport edit

# Runway(s) with ILS: (If any)

23

# References: (Official sources/charts)

http://acaa.gov.af/wp-content/uploads/2018/10/AIP-AIRAC-AMDT-004-2018-EFFECTIVE-DATE-08-NOV-2018-1.pdf

**Comment by MajorTomMueller** [comment]
Done, pullrequest #1115

**Comment by zhf21** [comment]
ILS no longer exists. Will be removed.

<img width="1440" alt="Screen Shot 2021-09-23 at 5 33 01 PM" src="https://user-images.githubusercontent.com/67797012/134587103-dc4ed548-9575-495c-a0b1-c2b5ee6b1b35.png">
