### ISSUE TITLE
EKVG-Vagar Airport-Faroe Islands-DENMARK

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1119]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Airport realigned with Satellite image

# Runway(s) with ILS: (If any)

< Enter text here >

# References: (Official sources/charts)

< Enter text here >

**Comment by kilt46** [comment]
Waypoints

SUDUR | 61.60303 | -7.08185
VG918 | 61.63314 | -7.11137
VG958 | 61.65498 | -7.13281
VG834 | 61.67736 | -7.1599
VG997 | 61.69924 | -7.16116
VG914 | 61.72409 | -7.08245
VG832 | 61.76808 | -7.20436
VG985 | 61.82857 | -7.14674
VG957 | 61.82894 | -7.14645
VG930 | 61.84483 | -7.06243
VG908 | 61.84961 | -6.8411
ROBUR | 61.8862 | -6.57648
D150K | 61.89703 | -6.96225
VG830 | 61.90132 | -7.20241
VG996 | 61.91247 | -7.23127
PEVAB | 61.92548 | -7.48534
D125R | 61.92677 | -6.73478
VG968 | 61.93329 | -7.20495
VG983 | 61.94759 | -6.8225
VG995 | 61.95044 | -7.12999
VG803 | 61.95112 | -7.27581
VG986 | 61.95287 | -7.1835
VG956 | 61.95598 | -7.044
CI30Z | 61.95864 | -6.85861
VG994 | 61.95865 | -7.20233
VG907 | 61.96459 | -6.88257
VG984 | 61.97747 | -7.02793
VG982 | 61.97936 | -6.92267
FI30Z | 61.98096 | -6.94697
VG904 | 61.98128 | -6.94856
VG946 | 61.98377 | -6.95805
VG993 | 61.98584 | -7.25562
VG981 | 61.99368 | -6.95879
VG998 | 61.99437 | -7.34973
VG818 | 62.0057 | -7.36373
VG992 | 62.00654 | -7.24824
VG999 | 62.01649 | -7.42105
VG944 | 62.01772 | -7.09316
VG866 | 62.02058 | -7.46432
VG814 | 62.02584 | -7.50004
VG991 | 62.02786 | -7.22418
VG942 | 62.02881 | -7.13749
VG980 | 62.03326 | -7.0589
VG805 | 62.03512 | -7.16274
VG978 | 62.03957 | -7.08869
VG976 | 62.04231 | -7.12788
VG | 62.04335 | -7.19566
VG812 | 62.04776 | -7.55514
VG974 | 62.04786 | -7.20813
VG972 | 62.05015 | -7.22303
VG990 | 62.05482 | -7.2418
RW30 | 62.05949 | -7.26057
VG900 | 62.05949 | -7.26057
VG864 | 62.06038 | -7.55567
DER30 | 62.06704 | -7.29097
RW12 | 62.06704 | -7.29097
VG901 | 62.06804 | -7.29499
VG903 | 62.07098 | -7.3108
VG807 | 62.0717 | -7.30976
VG804 | 62.07347 | -7.31935
VG854 | 62.074 | -7.32114
ML12 | 62.07534 | -7.33887
20LOC | 62.07654 | -7.34919
VG856 | 62.07654 | -7.33536
VG932 | 62.08038 | -7.61617
32LOC | 62.08134 | -7.39046
VG801 | 62.08311 | -7.39646
VG806 | 62.08911 | -7.44415
VG905 | 62.09024 | -7.46122
VG810 | 62.09317 | -7.47675
VG858 | 62.09701 | -7.43839
VG840 | 62.10041 | -7.53501
VG860 | 62.10221 | -7.4646
VG874 | 62.10338 | -7.5232
VG862 | 62.10458 | -7.49863
VG876 | 62.10523 | -7.57422
MY | 62.1069 | -7.58768
VG878 | 62.11137 | -7.62398
VG842 | 62.11199 | -7.62861
CL12 | 62.11211 | -7.65803
VG934 | 62.11839 | -7.73664
MAGNI | 62.13298 | -7.80042
D327D | 62.15143 | -7.66759

**Comment by ItsW1ll** [comment]
Added
