### ISSUE TITLE
VOMM

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#112]
Runway was moved. 
25/07 has an ils
12/30 doesn't have one

**Comment by dushyants19** [comment]
This might be helpful http://ivao.in/downloads/charts/2016/VOMF/VOMM/Layout.pdf

**Comment by dushyants19** [comment]
Changed elevation

**Comment by Adrien-Z** [comment]
I was supposed to fix it @indianbhaji. It's not a big deal for me, but please ask for assignment in the future. Thanks!
