### ISSUE TITLE
LTFM

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#1126]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

LTFM Created

# Runway(s) with ILS: (If any)

34L, 16R, 35R, 17L

# References: (Official sources/charts)

Contact Kilt if charts needed

**Comment by liamkirky** [comment]
I’ll have a look at this Bruno :)

**Comment by Czechoslovaki** [comment]
I'll be adding ILS to 18/36

**Comment by velocity23** [comment]
Up for grabs
