### ISSUE TITLE
VOMM VOR's

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#113]
There are about 3 VOR's in VOMM. 

Add if not already.

**Comment by NickArt1342** [comment]
@dushyants19 "about" 3 VOR's? Are there 3.24? Joking aside, I can't open the link provided by you and online databases only state very vague informations about VOR's I don't even know the name of.

**Comment by dushyants19** [comment]
Hmm, I was able to open this when I posted it. Sorry. Please search elsewhere

**Comment by NickArt1342** [comment]
@dushyants19 I can't add what i don't know at least the name of. There are literally double numbers of different VORs in the airports area and I don't want to add all of them right now nor do I know which ones you exactly want -.- Just give me the names and I'll get it done.

**Comment by dushyants19** [comment]
ItIt's probably named chennai. If you can't find close this.

**Comment by dushyants19** [comment]
Check if this works, 

http://www.ivao.in/pilots/charts/

[Layout.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/405577/Layout.pdf)

**Comment by Swang007** [comment]
Chennai (MVV) VOR is already in the file
Here are the navaids in the viscinity:
http://ourairports.com/navaids/MMV/Chennai_VOR-DME_IN/closest.html

**Comment by dushyants19** [comment]
OK

Can you add them? :)
