### ISSUE TITLE
SBBE

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#1140]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< Runway 06 >

# References: (Official sources/charts)

< https://www.aisweb.aer.mil.br/?i=aerodromos&codigo=SBBE
 http://ais.decea.gov.br/download/?arquivo=6f9ea2ae-23d8-1031-95e7-72567f175e3a&apikey=1587263166 >

**Comment by benjwri** [comment]
Fixed
