### ISSUE TITLE
RCSS

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Navigation#1148]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Runway moved, no ILS for 28 please remove

# References: (Official sources/charts)

http://eaip.caa.gov.tw/eaip/history/2018-12-06-AIRAC/html/index-en-TW.html?target=http%3A//eaip.caa.gov.tw/eaip/history/2018-12-06-AIRAC/html/eAIP/RC-AD-2.RCSS-en-TW.html%23AD-2.RCSS&menuState=http%3A//eaip.caa.gov.tw/eaip/history/2018-12-06-AIRAC/html/eAIP/RC-menu-en-TW.html,GEN,ENR,AD,AD-2,AD-2.RCSS

**Comment by ItsW1ll** [comment]
There is ILS on runway 10. I'll switch it around

**Comment by ItsW1ll** [comment]
fixed in dca237f
