### ISSUE TITLE
RCSS SID/STAR

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Navigation#1149]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

SALUN:250937.90N/1212036.60E 
ZONLI:245738.30N/1211223.68E
FUTER:245936.45N/1212011.81E 
KIRIN:250435.25N/1212029.73E
LUCHO:250423.10N/1212703.86E
RWY10:250412.18N/1213222.64E
OSCAR:250355.40N/1213755.30E
KILON:250822.00N/1214803.00E
PINSI:250233.10N/1215018.19E
THEOD:251117.17N/1214539.48E
DAVIE:250630.17N/	1214718.93E
DF5.0:250553.62N/1214512.98E
DF2.0:250458.74N/1214204.08E
JOHNT:250422.12N/1213958.17E
DF3.8:250419.19N/1213857.11E
VANES:250407.12N/1213445.44E
RWY28:250408.89N/1213355.53E
DENIS:250421.70N/1212751.94E
BERES:245852.04N/1214749.68E
GLEAM:250401.00N/1213809.00E 
TRINO:250010.00N/1214343.00E 
KUMAR:250422.00N/1212752.00E 
SASHA:245522.69N/1212445.07E 
YILAN:244426.00N/1214731.00E
DICTA:250428.35N/1212440.40E 
LOBAR:251259.76N/1213029.03E 
SENNA:252157.26N/1214000.16E 
VIVID:253315.39N/1214840.73E
BESOM:250543.00N/1215134.00E
DUPAR:251335.13N/1215201.57E
FUSIN:245141.39N/1212937.35E
JONHO:245453.84N/1211826.18E
JUNTO:250550.78N/1215211.59E
LU:250822.10N/1214803.30E
SG:250413.5N/1213146.5E
PUTIN:244709.00N/1205949.00E

# References: (Official sources/charts)

http://eaip.caa.gov.tw/eaip/history/2018-12-06-AIRAC/html/index-zh-TW.html

**Comment by aads552** [comment]
By the way, there are some waypoints without coordinates. Only degrees and distance from VOR provided. Is there anyway to calculate the correct coordinates of those waypoints?

**Comment by ItsW1ll** [comment]
Umm, which ones are they?

**Comment by aads552** [comment]
I didn't put them here.
Here they are, all available in charts:

WUGOO(TSI R-277/8D)
BITAN(TSI R-190/8D)
SITZE(SG 100BRG 6D)
MUKKA(TSI R-120/4D)
RONEO(APU R-225/40D)
XEBEC(APU R-203/49D)
SULIN(SG 260BRG 6D)
COOKY(APU R-215/22D)
ATOLL(APU R-053/11D)
SIDIN(APU R-140/19D)
TAZAN(ITSG 10.7D)
REFON(ITLU 13D)

(ITSG:250408.6N/1213404.6E, ITLU:250405.0N/1213356.5E)

**Comment by ItsW1ll** [comment]
Okay most of those are in the file already. just RWY10/RWY28

**Comment by aads552** [comment]
Thanks, any problem with those two?

**Comment by ItsW1ll** [comment]
@aads552 I will add the "RWY" fixes. Would you mind checking if some of them have been added in the update?
