### ISSUE TITLE
VOCI

### ISSUE THREAD

**Issue by akshay2777** [InfiniteFlightAirportEditing/Navigation#1162]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

09/27

# References: (Official sources/charts)
https://aim-india.aai.aero/sites/default/files/aip_supplements/AIPS_2018_159.pdf
https://aim-india.aai.aero/eaip-v2//25-05-2017/eAIP/EC-AD-2.1VOCI-en-GB.pdf
https://aim-india.aai.aero/sites/default/files/aip_supplements/AIPS_2018_97.pdf

**Comment by Balloonchaser** [comment]
#1217

**Comment by Czechoslovaki** [comment]
Runway 09 ILS added.
