### ISSUE TITLE
SPHY

### ISSUE THREAD

**Issue by danisrils39** [InfiniteFlightAirportEditing/Navigation#1170]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

21

# References: (Official sources/charts)

![image](https://user-images.githubusercontent.com/8258998/52171864-cabc6f00-2729-11e9-943b-4ef19f5df778.png)

**Comment by benjwri** [comment]
Fixed
