### ISSUE TITLE
RJTA

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1175]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 01 >

# References: (Official sources/charts)

<http://tomoroku.sakura.ne.jp/AIP2014/Atsugi%20%8C%FA%96%D8%20RJTA.pdf >

**Comment by benjwri** [comment]
Already fixed
