### ISSUE TITLE
RJOT

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1176]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 26 >

# References: (Official sources/charts)

< http://tomoroku.sakura.ne.jp/AIP2014/Takamatsu%20%8D%82%8F%BC%20RJOT.pdf >

**Comment by benjwri** [comment]
Fixed by someone in previous update
