### ISSUE TITLE
RJFN

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1177]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 28 >

# References: (Official sources/charts)

< http://tomoroku.sakura.ne.jp/AIP2014/Nyutabaru%20%90V%93c%8C%B4%20RJFN.pdf >

**Comment by benjwri** [comment]
This has been fixed by someone in a previous update
