### ISSUE TITLE
RJFY

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1178]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 26L >

# References: (Official sources/charts)

< https://yinlei.org/x-plane10/doc/AIP-J/RJFY_Kanoya.pdf >

**Comment by Velocity23** [comment]
Will work on this

**Comment by Velocity23** [comment]
Appears to be already correct except the coordinates were a 1000000th off. Will make PR later.
