### ISSUE TITLE
EGVN 

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Navigation#1189]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

07/25

# References: (Official sources/charts)

https://www.raf.mod.uk/our-organisation/stations/raf-brize-norton/documents/royal-air-force-brize-norton-defence-aerodrome-manual/

Looks like ILS is lost after Runwaynumber change

**Comment by orangejuicie** [comment]
I fixed this.
