### ISSUE TITLE
TAPA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#119]
Approach fixes look a bit off, probably because airport was realigned a few months ago?

**Comment by NickArt1342** [comment]
But the fixes aren't alligned to the airport but to RL data, so when the airport is where it is in RL it should be all fine

**Comment by Swang007** [comment]
That's true... But is the previous RL data lined up with Bing maps?

**Comment by NickArt1342** [comment]
I have no idea :P You're here longer than I was: You should know :P If you mind telling me the all the names of the fixes I'll go check them.
