### ISSUE TITLE
OTU-(VOR-DME) Suggestion

### ISSUE THREAD

**Issue by airbus3d** [InfiniteFlightAirportEditing/Navigation#1194]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

VOR

# Runway(s) with ILS: (If any)

N/A

# References: (Official sources/charts)

http://ourairports.com/navaids/OTU/Otumba_VOR-DME_MX/#lat=19.6830997467041,lon=-98.77639770507812,zoom=10,type=Satellite

**Comment by ItsW1ll** [comment]
VOR has been removed from IF due to it being removed in real life. if you need more info please pm me on slack :)
