### ISSUE TITLE
UUOO

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1197]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 30 >

**Comment by orangejuicie** [comment]
I fixed this.

**Comment by AleksanderIF** [comment]
ILS 12 missing - http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uuoo/1-ad2-rus-uuoo-097.pdf
