### ISSUE TITLE
LFPB

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#12]
Some kind of heading bug? Need to see if this is an ILS or GPS approach.

https://community.infinite-flight.com/t/lfpb-gps-approach-bug/9791

**Comment by DavidCutler** [comment]
The heading should be correct as it shows runway 27 for LFPB as of now.

**Comment by henrikbg** [comment]
Still an issue.

https://community.infinite-flight.com/t/lfpb-ils-approach-bug/9791/14?u=henrik

**Comment by henrikbg** [comment]
Should be fixed now in b59640f.

**Comment by GBKarp** [comment]
Can this be reopened? I'll do it
