### ISSUE TITLE
TJSJ 

### ISSUE THREAD

**Issue by Blently** [InfiniteFlightAirportEditing/Navigation#120]
I moved runway 08/26 just a little bit.

**Comment by Swang007** [comment]
Can't do this one until it's committed to the Airports repo

**Comment by bylrret** [comment]
It's ok, at least you know :)

**Comment by Swang007** [comment]
Oh wait, it's been there for a week haha

**Comment by Swang007** [comment]
Adjusted ILS for 08 and 10

**Comment by Blently** [comment]
Runways were moved during editing. 08/26 10/28 both ILS

**Comment by TristinWoolf** [comment]
I'll take this one.

**Comment by Adrien-Z** [comment]
Fixed by @TristinWoolf in 07df6b8.
