### ISSUE TITLE
CYZR

### ISSUE THREAD

**Issue by orangejuicie** [InfiniteFlightAirportEditing/Navigation#1204]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS/LOC >

# Runway(s) with ILS: (If any)

< ILS33/LOC15 >

**Comment by orangejuicie** [comment]
I fixed this.

**Comment by zhf21** [comment]
No proof of either an ILS or LOC.

<img width="1440" alt="Screen Shot 2021-09-29 at 12 49 30 PM" src="https://user-images.githubusercontent.com/67797012/135313579-a3a0d0d2-1ee6-4a06-b2e9-c214eb67cfda.png">
