### ISSUE TITLE
Alabama Fixes Update AIRAC 1904

### ISSUE THREAD

**Issue by 2018ljh** [InfiniteFlightAirportEditing/Navigation#1209]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Fixed fixes as per approach charts and DPs.

# Runway(s) with ILS: (If any)

< Enter text here >

# References: (Official sources/charts)

http://www.airmate.aero/

**Comment by ItsW1ll** [comment]
has this already been committed?

**Comment by 2018ljh** [comment]
I don’t think so. To my knowledge, it has been merged with the master branch, but not committed to my knowledge.
