### ISSUE TITLE
UHHH

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#121]
Need to adjust ILS for runways 05R & 23L once airport is in the repository

**Comment by dushyants19** [comment]
It is in the repo @swang007

**Comment by Swang007** [comment]
Thanks!

**Comment by AleksanderIF** [comment]
ILS rwy 05L/23R 
[_.archivetempI-2_UHHH.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5816757/_.archivetempI-2_UHHH.pdf)
[_.archivetempI-7_UHHH.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5816758/_.archivetempI-7_UHHH.pdf)
(Will do it later)
