### ISSUE TITLE
CYKF-Waterloo Airport-ONTARIO-CANADA

### ISSUE THREAD

**Issue by Balloonchaser** [InfiniteFlightAirportEditing/Navigation#1213]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Runway 26 ILS Added @ CYKF >

# Runway(s) with ILS: (If any)

< 26 >

# References: (Official sources/charts)

< https://skyvector.com/airport/CYKF/Kitchener-Waterloo-Airport >

**Comment by RyanEpps** [comment]
#1214
