### ISSUE TITLE
VILK

### ISSUE THREAD

**Issue by Ayush-19** [InfiniteFlightAirportEditing/Navigation#1227]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Moved runway during editing.

# Runway(s) with ILS: (If any)

09/27

# References: (Official sources/charts)

https://aim-india.aai.aero/eaip-v2//25-05-2017/eAIP/EC-AD-2.1VILK-en-GB.pdf (last few pages, would be most helpful)

**Comment by kztmtn** [comment]
Only RWY27 equipped ILS.
