### ISSUE TITLE
SBCT

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1233]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

RWY 15 and RWY 33

# References: (Official sources/charts)

RWY 15: http://ais.decea.gov.br/download/?arquivo=3414edf9-5525-4c25-bfc9f3ecfd2ecd34&apikey=1587263166

RWY 33: http://ais.decea.gov.br/download/?arquivo=9dbe3c9e-60b2-43c6-973289bce653cc1a&apikey=1587263166

**Comment by MBeringuy** [comment]
In the case of this airport, currently only runway 33 is without ILS in the simulator.

**Comment by zhf21** [comment]
RWY 15 -> Cat-II

<img width="400" alt="Screen Shot 2021-09-27 at 8 22 34 PM" src="https://user-images.githubusercontent.com/67797012/135002564-e6d2ba4d-34ff-44dc-83fc-c389bf36e8ad.png">
