### ISSUE TITLE
Missing waypoints near ORAA

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Navigation#1250]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Adding 18 missing waypoints near ORAA airport

# References: (Official sources/charts)

**CR33L**: 33.129917N 44.311889E
**D094L**: 33.755806N 42.680444E
**D253L**: 33.745500N 42.208917E 
**GIRBO**: 33.796917N 42.575000E
**IMDUD**: 33.797806N 42.324167E
**ITRIL**: 33.792444N 42.574583E
**KUMUM**: 33.750528N 42.187389E
**KUVRA**: 33.816583N 42.105306E
**LUDOB**: 33.811667N 42.782250E
**MIVUT**: 33.805472N 42.694556E
**NAGER**: 33.787278N 42.336722E
**ORGUV**: 33.739056N 42.108611E
**ORMUS**: 33.808111N 42.204806E
**RIGAK**: 33.587778N 42.422639E
**TARLO**: 33.789250N 42.423083E
**TUKIG**: 33.758806N 42.562639E
**TUDIT**: 33.780333N 42.394250E
**ULBIG**: 33.781861N 42.466583E

[Navigraph](https://charts.navigraph.com/)

**Comment by SpaceGuru01** [comment]
Are you working on this or do you want me to add them?
