### ISSUE TITLE
Missing ORAA VOR (RAA)

### ISSUE THREAD

**Issue by pilot0674** [InfiniteFlightAirportEditing/Navigation#1251]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Missing VOR for ORAA

# References: (Official sources/charts)

**RAA - AL ASAD (AL-ANBAR)**: 33.787389N 42.443500E

[Navigraph](https://charts.navigraph.com/)

**Comment by SpaceGuru01** [comment]
I can add this if you want or are you working on it?

**Comment by ItsW1ll** [comment]
It is a tacan and at this time will not be added to the vor file as it is not compatible with the format
