### ISSUE TITLE
SBGR runways moved

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Navigation#127]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/75

Not sure if they are ILS or not.

**Comment by NickArt1342** [comment]
@samuelandersson FYI: all runways are ILS in sao paulo ;)

**Comment by samuelandersson** [comment]
Thanks for info @NickArt1342 :)

**Comment by zhf21** [comment]
Cat-III ILSes need to be implemented + fixes.

<img width="1440" alt="Screen Shot 2021-09-27 at 9 32 58 PM" src="https://user-images.githubusercontent.com/67797012/135007770-f534d3c3-bae6-4e1e-858a-e2dbb9359e94.png">
