### ISSUE TITLE
VOR CDY Missing

### ISSUE THREAD

**Issue by Velocity23** [InfiniteFlightAirportEditing/Navigation#1282]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

VOR CHEDAOYU (CDY, China) is missing

# References: (Official sources/charts)

https://skyvector.com

**Comment by ItsW1ll** [comment]
I will close the pull request as the VOR doesn't exist. Checked skyvector and CDY is a NDB which exists in game. Drop me a message on slack if you have any issues
