### ISSUE TITLE
EGNT

### ISSUE THREAD

**Issue by Velocity23** [InfiniteFlightAirportEditing/Navigation#1291]
♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS Moved after redo

**Comment by Velocity23** [comment]
Never mind, appears to have been fixed

**Comment by kztmtn** [comment]
https://www.aurora.nats.co.uk/htmlAIP/Publications/2018-12-06-AIRAC/html/eAIP/EG-AD-2.EGNT-en-GB.html

RWY 07/25 CAT III
