### ISSUE TITLE
UUEE

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#130]
Need to adjust ILS for runways, once airport is in the repository

**Comment by sentikum** [comment]
http://files.ivaoru.org/charts/uuee.pdf

That is Information about airport

**Comment by henrikbg** [comment]
Updated in b3765be.

**Comment by ItsW1ll** [comment]
ILS needs adding again.

**Comment by ewanfleming** [comment]
Fixed in https://github.com/InfiniteFlightAirportEditing/Navigation/commit/89a06b427ac54882be5587c750c7292097dae16f

**Comment by kilt46** [comment]
UUEE 3rd runway added. 06L/24R. Rename central runway 06C/24C
