### ISSUE TITLE
EGLL

### ISSUE THREAD

**Issue by Velocity23** [InfiniteFlightAirportEditing/Navigation#1323]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Not sure when this was last updated but needs a fix

# Runway(s) with ILS: (If any)

All (27R, 27L, 09R, 09L)

# References: (Official sources/charts)

https://vau.aero/navdb/chart/EGLL.pdf

**Comment by Velocity23** [comment]
Working on this

**Comment by kztmtn** [comment]
I'll fix this, RWY moved during redo.
