### ISSUE TITLE
LIPB

### ISSUE THREAD

**Issue by Velocity23** [InfiniteFlightAirportEditing/Navigation#1329]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS angle is incorrect. should be 5 degrees instead of 3. 

# Runway(s) with ILS: (If any)

01

# References: (Official sources/charts)

https://community.infiniteflight.com/t/wrong-ils-angle-at-bolzano/415701

**Comment by Velocity23** [comment]
Working on this

**Comment by Velocity23** [comment]
Seems to be up to date. No idea what went wrong

**Comment by ItsW1ll** [comment]
Regarding this issue I have added a glide-slope entry for this LOC so that it is a 5 degrees slope. A better fix may have to be implemented later on.
