### ISSUE TITLE
ZBAD 

### ISSUE THREAD

**Issue by MajorTomMueller** [InfiniteFlightAirportEditing/Navigation#1351]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

adding Fixes for ZBAD

# Runway(s) with ILS: (If any)

several, but ILS is already done

# References: (Official sources/charts)

ZBAD AIP, and Navigraph

**Comment by MajorTomMueller** [comment]
Will do this.

**Comment by MajorTomMueller** [comment]
done https://github.com/InfiniteFlightAirportEditing/Navigation/pull/1352/commits/b39126ad51ff712c49e4846c725af2dfd279f824

**Comment by MajorTomMueller** [comment]
have to do again while I messed up my branch.

**Comment by ItsW1ll** [comment]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS errors with ZBAD

# Runway(s) with ILS: (If any)

35C 29R
