### ISSUE TITLE
EDDM Waypoints and Navaids

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#136]
Link to a form with the Waypoints around Munich: http://opennav.com/pdf/EDDM/ED_AD_2_EDDM_6_en_2013-03-07.pdf
Navaids around Munich are listed at the bottom of the following page:
http://opennav.com/airport/EDDM

**Comment by henrikbg** [comment]
That's an awful lot of waypoints and VORs. We'll get to them after global flight is released since we can't check properly if they're there or not.

**Comment by Swang007** [comment]
Some of these documents are 7 years old. Are the waypoints still accurate?

**Comment by henrikbg** [comment]
We'll have a look over this once we can get accurate and up to date charts. Until then, we can call this closed.

**Comment by moritzbabl** [comment]
I now have a up-to-date waypoint list, will check the NDBs,VORs and Fixes and add missing ones

**Comment by moritzbabl** [comment]
added and edited, now finally done
