### ISSUE TITLE
RJTT

### ISSUE THREAD

**Issue by aads552** [InfiniteFlightAirportEditing/Navigation#1366]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 22, 23, 34R, 34L >

# References: (Official sources/charts)

Runway moved during redo

https://aisjapan.mlit.go.jp/html/AIP/html/20191205/eAIP/20191205/JP-AD-2-RJTT-en-JP.html#RJTT-AD-2.19

**Comment by benjwri** [comment]
Fixed
