### ISSUE TITLE
LOWI

### ISSUE THREAD

**Issue by IceBlue02** [InfiniteFlightAirportEditing/Navigation#137]
Runway moved slightly, ILS to 3.5 degrees both sides.

**Comment by henrikbg** [comment]
Updated in bb753f2.

**Comment by dushyants19** [comment]
Runway headings for ILS are swapped (Its ~60 for R27)

**Comment by IceBlue02** [comment]
It's correct. Quoting from the AIP:

A bi-directional localizer (OEJ 109,70 MHZ, Frontbeam 066° MAG, Backbeam 064° MAG) located 10 NM ENE of the aerodrome, and offset
from the runway centre line, is provided for the instrument flight segment of the descent procedure.'

After that pilots make a right 180+ turn for a visual to 08 or 26.

How we handle this in IF I don't know...

**Comment by dushyants19** [comment]
Makes a circle and Autoland wont work

**Comment by IceBlue02** [comment]
But auto land wouldn't be used in real life anyway...

I say it's left. Realistic approaches FTW

**Comment by dushyants19** [comment]
Best to leave it like this.

**Comment by ItsW1ll** [comment]
Heading is wrong hence auto land won't work.

**Comment by ItsW1ll** [comment]
RWY 26 needs a look into
