### ISSUE TITLE
LTBQ

### ISSUE THREAD

**Issue by rich-art-02** [InfiniteFlightAirportEditing/Navigation#1395]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

27

# References: (Official sources/charts)

[LT_AD_2_LTBQ_IAC_06_en.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4193869/LT_AD_2_LTBQ_IAC_06_en.pdf)

**Comment by benjwri** [comment]
Fixed
