### ISSUE TITLE
PHNY

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#140]
03 has an ILS

http://www.airnav.com/airport/PHNY

**Comment by henrikbg** [comment]
Runway 03 at Lanai has an ILS in the navigation files. There's probably some updating that needs to be done on the developer side.

By the way, I updated the ILS data in c248e88.

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

03

# References: 

https://flightaware.com/resources/airport/PHNY/IAP/ILS+OR+LOC_DME+RWY+03

**Comment by ItsW1ll** [comment]
03 needs to be changed to 3
