### ISSUE TITLE
LTCR

### ISSUE THREAD

**Issue by gzhynko** [InfiniteFlightAirportEditing/Navigation#1408]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Moved runway during editing, ILS, LOC

# Runway(s) with ILS: (If any)

03

# References: (Official sources/charts)

[LTCR](https://user-images.githubusercontent.com/28837858/75881334-e2d05780-5e2f-11ea-8afe-6a0f680425b0.jpg)

**Comment by benjwri** [comment]
Fixed
