### ISSUE TITLE
KPDX [KRATR2 STAR] Missing Waypoints

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#142]
HYKER and SHYNE are missing to my knowledge. You can check for the others in case they're missing as well. 

This is the best chart I could find (Sorry I couldn't find one with coordinates).

http://flightaware.com/resources/airport/PDX/STAR/KRATR+TWO+(RNAV)/pdf

**Comment by henrikbg** [comment]
Could you try to find one with coordinates of some sort? I can't add them without it :/

**Comment by dushyants19** [comment]
http://opennav.com/waypoint/US/HYKER

http://opennav.com/waypoint/US/SHYNE

**Comment by CptNathanHope** [comment]
Thank you @dushyants19 :)

**Comment by henrikbg** [comment]
Added in 1d722da.
