### ISSUE TITLE
KAUO

### ISSUE THREAD

**Issue by jasonbburks** [InfiniteFlightAirportEditing/Navigation#1426]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

No ILS on runway 30-18 

# Runway(s) with ILS: (If any)

< 30-18 >

# References: (Official sources/charts)

< Airnav, FAA charts, personal use of ILS at Auburn >

**Comment by ItsW1ll** [comment]
Airport hasn't yet been edited

**Comment by Czechoslovaki** [comment]
I'll fix the ILS.
