### ISSUE TITLE
KMRY

### ISSUE THREAD

**Issue by jakey200** [InfiniteFlightAirportEditing/Navigation#1448]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

10R: ILS
28L: LOC

# References: (Official sources/charts)

https://aeronav.faa.gov/d-tpp/2004/00271IL10R.PDF
https://aeronav.faa.gov/d-tpp/2004/00271L28L.PDF

**Comment by benjwri** [comment]
Fixed
