### ISSUE TITLE
VVPQ

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1456]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 10/28 >

# References: (Official sources/charts)

< m 
![60BC406E-0B34-4979-B9D7-7E3FF33FBA48](https://user-images.githubusercontent.com/43931356/79127888-d34c1300-7dcc-11ea-863a-eedeb07213b8.jpeg)

![57D05F1E-B090-4924-9D35-5F9A16AFAE2A](https://user-images.githubusercontent.com/43931356/79127793-b3b4ea80-7dcc-11ea-96d5-2faf45dce491.jpeg)
 >

**Comment by benjwri** [comment]
Fixed
