### ISSUE TITLE
VVCR

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1468]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 02 >

# References: (Official sources/charts)

< 
![1B7C2F70-8B28-4A3C-8949-4F9CBDD5FE29](https://user-images.githubusercontent.com/43931356/79642314-fb6db480-81c6-11ea-8692-bde8629c836e.png)

**Comment by AnthonyCK** [comment]
Fixed
