### ISSUE TITLE
VVCT

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1469]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 06 >

# References: (Official sources/charts)

< 
![935339B1-5028-49EE-82BB-9631B24C0B69](https://user-images.githubusercontent.com/43931356/79642385-56071080-81c7-11ea-8b7d-0447023eb8bb.jpeg)
>

**Comment by AnthonyCK** [comment]
Runway Number is incorrect in the latest apt.dat file. 
[https://github.com/InfiniteFlightAirportEditing/Airports/blob/development/Vietnam/VVCT/apt.dat](url)
![image](https://user-images.githubusercontent.com/37546244/79981473-50673e80-84d7-11ea-86cc-686352ba5e05.png)

**Comment by IFUA2003** [comment]
I will fix that

**Comment by IFUA2003** [comment]
Changed
