### ISSUE TITLE
SBPO

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#1471]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< IAP and SID Waypoints >

# Runway(s) with ILS: (If any)

< None >

# References: (Official sources/charts)

< SID RWY 07: http://ais.decea.gov.br/download/?arquivo=b55bee02-60c1-4327-acd24af81bc7fadc&apikey=1587263166 Coordinates: http://www.aisweb.aer.mil.br/download/?tabela=b61db2c8-2d16-4ce0-acb5cce3ce762c0a&t=PO00C
    SID RWY 25: http://ais.decea.gov.br/download/?arquivo=fc59c9de-ddc0-4b7e-ba599d6a66678cfa&apikey=1587263166 Coordinates: http://www.aisweb.aer.mil.br/download/?tabela=012f2553-7c26-48b2-a9e9326a6dd7b8cb&t=PO00D
    IAP RWY 07: http://ais.decea.gov.br/download/?arquivo=a1825598-3214-49dc-84243965741adc37&apikey=1587263166 Coordinates: http://www.aisweb.aer.mil.br/download/?tabela=b6ad40b1-f004-4254-9e314bbc569ada09&t=PO00A 
    IAP RWY 25: http://ais.decea.gov.br/download/?arquivo=891df8c2-8f8e-4cf9-8c7df6dbbb9d9b5f&apikey=1587263166 Coordinates: http://www.aisweb.aer.mil.br/download/?tabela=fb9b7854-45f4-4641-ba3be9e43b63d27e&t=PO00B >

**Comment by AnthonyCK** [comment]
I believe these waypoints are already in the database.

**Comment by FellipeEdu** [comment]
Oh, yes! I forgot to check, sorry and thank you :)
