### ISSUE TITLE
VVTX

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Navigation#1474]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Runway 31

# References: (Official sources/charts)

https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/DAP-Viet-Nam/DAP%20website%20BDKT/Related%20Links/DAP/pdf/VVTX.pdf

**Comment by AnthonyCK** [comment]
Fixed
