### ISSUE TITLE
VVVH

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Navigation#1475]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Runway 17

# References: (Official sources/charts)

https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/DAP-Viet-Nam/DAP%20website%20BDKT/Related%20Links/DAP/pdf/VVVH.pdf

**Comment by AnthonyCK** [comment]
Fixed
