### ISSUE TITLE
VVPQ

### ISSUE THREAD

**Issue by MinhNguyN** [InfiniteFlightAirportEditing/Navigation#1476]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Runway 10 & Runway 28

# References: (Official sources/charts)

https://vnaic.vn/images/stories/vnaic.vn/SanPhamDichVu/AIP-SUP/esup-19-a28_approvedbycaav.pdf

**Comment by AnthonyCK** [comment]
Fixed
