### ISSUE TITLE
KBHM

### ISSUE THREAD

**Issue by brennanhackard** [InfiniteFlightAirportEditing/Navigation#1483]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

06, 24, 18

# References: (Official sources/charts)
[https://flightaware.com/resources/airport/KBHM/IAP/ILS+RWY+06+(CAT+II)](url)
[https://flightaware.com/resources/airport/KBHM/IAP/ILS+RWY+24+(SA+CAT+II)](url)
[https://flightaware.com/resources/airport/KBHM/IAP/LOC+RWY+18](url)

**Comment by jakey200** [comment]
Fixes in #1499
