### ISSUE TITLE
URMM

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1488]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 12/30 >

# References: (Official sources/charts)

< RWY12
![image](https://user-images.githubusercontent.com/53284798/80284788-45a3e800-8729-11ea-8854-e6dc27f98112.png)
RWY30
![image](https://user-images.githubusercontent.com/53284798/80284807-679d6a80-8729-11ea-8bbc-3e35e086cdce.png)
 >

**Comment by AnthonyCK** [comment]
Fixed :D 
However, I do recommend you provide the full IAP page or pages including information in the red frame of the image below next time. :)
![URMM](https://user-images.githubusercontent.com/37546244/80307796-f67bb700-87fd-11ea-8a66-13597be0ca61.png)

**Comment by AleksanderIF** [comment]
Ok
