### ISSUE TITLE
DAAG

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Navigation#1494]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
< Enter text here >

# Runway(s) with ILS: (If any)
27
< Enter text here >

# References: (Official sources/charts)
[ILS.DAAG-converti.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4545720/ILS.DAAG-converti.pdf)

< Enter text here >

**Comment by tonyi31** [comment]
hello 
just information how long to add ILS

**Comment by AnthonyCK** [comment]
Already added.

**Comment by tonyi31** [comment]
my not yet on the Infinity Flight

**Comment by tonyi31** [comment]
thank you

**Comment by AleksanderIF** [comment]
it will be in IF, after navigation update comes out

**Comment by tonyi31** [comment]
thank you

**Comment by tonyi31** [comment]
hello put navigation exit my always it not ILS

**Comment by jakey200** [comment]
The ILS does not show in the simulator?

**Comment by tonyi31** [comment]
has this good maintained thank you very much

**Comment by MajorTomMueller** [comment]
issue could be closed ILS is propper set up and shows up in IF
