### ISSUE TITLE
DAOO

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Navigation#1496]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS

# Runway(s) with ILS: (If any)
25L/25R

# References: (Official sources/charts)

Jeppesen Chart

<img width="381" alt="ILS 25L" src="https://user-images.githubusercontent.com/63318768/106245047-23854c00-620c-11eb-9794-4e9d5b9c017a.png">
<img width="530" alt="ILS 25R" src="https://user-images.githubusercontent.com/63318768/106245066-2c761d80-620c-11eb-9781-93eb1e6e197e.png">

**Comment by AnthonyCK** [comment]
Has this airport passed OR? If not, please create a navigation issue **AFTER** your airport has passed OR next time :)

**Comment by tonyi31** [comment]
> Cet aéroport est-il passé OU? Sinon, veuillez créer un problème de navigation **APRÈS le passage de** votre aéroport OU la prochaine fois :)

HELLO
as she passed or I understood

**Comment by velocity23** [comment]
Needs to be updated before it's worth working on, I'll put this on hold for now

**Comment by MBeringuy** [comment]
Airport redone. I will do this.

**Comment by tonyi31** [comment]
yes if possible thank you

Envoyé de mon iPad

**Comment by falous** [comment]
Helli 
possible add second ILS 25L please thank you

**Comment by velocity23** [comment]
ILS 25L still needs doing.
Source: https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAOO/IAC5.pdf

**Comment by tonyi31** [comment]
very clear to THEM thank you very much
