### ISSUE TITLE
ENRA

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Navigation#1497]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway with ILS created

# Runway(s) with ILS: (If any)

32

# References: (Official sources/charts)

https://web.archive.org/web/20120730015511/https://www.ippc.no/norway_aip/current/AIP/AD/ENRA/EN_AD_2_ENRA_en.pdf

**Comment by jakey200** [comment]
Fixed
