### ISSUE TITLE
VVPK

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1508]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 27 >

# References: (Official sources/charts)

< 
![1B0FE5AB-7AB5-4467-B237-FE2A4B253EB3](https://user-images.githubusercontent.com/43931356/80864535-806bca00-8cad-11ea-8714-a218d14d3007.jpeg)
>

**Comment by brennanhackard** [comment]
Fixed in #1504
