### ISSUE TITLE
VVBM

### ISSUE THREAD

**Issue by TaiXipo13** [InfiniteFlightAirportEditing/Navigation#1509]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 09 >

# References: (Official sources/charts)

< 
![380B5B6D-DCD9-4A98-9370-67157734D4ED](https://user-images.githubusercontent.com/43931356/80864564-bc9f2a80-8cad-11ea-8909-fb9443ad75cb.jpeg)
 >

**Comment by brennanhackard** [comment]
Fixed in #1504

**Comment by IFUA2003** [comment]
I moved runway 09, please fix it

**Comment by zhf21** [comment]
I can fix this. :)
