### ISSUE TITLE
SBCF

### ISSUE THREAD

**Issue by jakey20** [InfiniteFlightAirportEditing/Navigation#1517]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

16

# References: (Official sources/charts)

Navigraph

**Comment by jakey200** [comment]
fixed in #1516

**Comment by MBeringuy** [comment]
Source: https://aisweb.decea.mil.br/?i=cartas&amdt=2021-03-25
