### ISSUE TITLE
KDSM

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1521]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

5, 13, 31

# References: (Official sources/charts)

5: https://skyvector.com/files/tpp/2005/pdf/00117IL5.PDF

13: https://skyvector.com/files/tpp/2005/pdf/00117IL13.PDF

31: https://skyvector.com/files/tpp/2005/pdf/00117IL31.PDF

**Comment by brennanhackard** [comment]
I'll fix this

**Comment by brennanhackard** [comment]
Fixed in #1504
