### ISSUE TITLE
LEBL

### ISSUE THREAD

**Issue by kztmtn** [InfiniteFlightAirportEditing/Navigation#1525]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

02, 07L/25R, 07R/25L

# References: (Official sources/charts)

[ILS Z RWY 02.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4586937/ILS.Z.RWY.02.pdf)
[ILS Z RWY 07L.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4586938/ILS.Z.RWY.07L.pdf)
[ILS Z RWY 07R.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4586940/ILS.Z.RWY.07R.pdf)
[ILS Z RWY 25L.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4586943/ILS.Z.RWY.25L.pdf)
[ILS Z RWY 25R.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4586945/ILS.Z.RWY.25R.pdf)

**Comment by jakey200** [comment]
fixed in #1516
