### ISSUE TITLE
LFMH

### ISSUE THREAD

**Issue by bavariaaviation** [InfiniteFlightAirportEditing/Navigation#1532]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

runway with ILS created

# Runway(s) with ILS: (If any)

17/35
(glideslope gradient for 35 is 3.80)

# References: (Official sources/charts)

https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_23_APR_2020/FRANCE/AIRAC-2020-04-23/pdf/FR-AD-2.LFMH-fr-FR.pdf

**Comment by AnthonyCK** [comment]
This airport has no ILS equipment I believe :( @bavariaaviation 
![image](https://user-images.githubusercontent.com/37546244/82072067-96e03f80-9709-11ea-9747-1623ba5a173b.png)
