### ISSUE TITLE
VVCI

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1534]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 07

# References: (Official sources/charts)

<
![2811B563-ED15-4B44-A737-9D7A9FCD85AB](https://user-images.githubusercontent.com/43931356/81885764-465fc980-95c5-11ea-8b35-c84f0c3bba29.jpeg)
 >

**Comment by brennanhackard** [comment]
I'll fix this.

**Comment by brennanhackard** [comment]
fixed in #1538
