### ISSUE TITLE
KLMT

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1537]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

I L S

# Runway(s) with ILS: (If any)

32

# References: (Official sources/charts)

https://skyvector.com/files/tpp/2005/pdf/00473ILD32.PDF

**Comment by brennanhackard** [comment]
I'll fix this.

**Comment by brennanhackard** [comment]
fixed #1538
