### ISSUE TITLE
ESNU

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Navigation#154]
Runway moved during redo. ILS runway 14 or 32.

**Comment by dushyants19** [comment]
cant find this too

**Comment by henrikbg** [comment]
Updated in 6dce673.

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

14/32

# References: 

https://www.aro.lfv.se/Editorial/View/IAIP?folderId=65
