### ISSUE TITLE
KRFD

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1546]
# Summary of Navigation issue: (ILS, Waypoints, etc)

Instrument Landing System

# Runway(s) with ILS: (If any)

1, 7

# References: (Official sources/charts)

1: https://skyvector.com/files/tpp/2005/pdf/00954IL1.PDF

7: https://skyvector.com/files/tpp/2005/pdf/00954IL7.PDF

**Comment by brennanhackard** [comment]
I'll fix this

**Comment by brennanhackard** [comment]
fixed in #1538
