### ISSUE TITLE
UHPP

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1553]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 16R, 34L >

# References: (Official sources/charts)

< 
![Screenshot_20200521_015534](https://user-images.githubusercontent.com/53284798/82505607-d2627b80-9b06-11ea-8883-dfde9220d4cf.jpg)
![Screenshot_20200521_015506](https://user-images.githubusercontent.com/53284798/82505608-d393a880-9b06-11ea-98c8-20ee4b8c97bd.jpg)
>

**Comment by jakey200** [comment]
Has this airport been redone yet?

**Comment by AleksanderIF** [comment]
Airport was redone, but it was 2 years ago. Or it need to be redone to add ILS?
