### ISSUE TITLE
KPDX

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1569]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

10L 10R 28L 28R

# References: (Official sources/charts)

10L: https://airportdocs.iflightplanner.com/2006/00330IL10L.PDF
10R: https://airportdocs.iflightplanner.com/2006/00330IL10R.PDF
28L: https://airportdocs.iflightplanner.com/2006/00330IL28L.PDF
28R: https://airportdocs.iflightplanner.com/2006/00330IL28R.PDF

**Comment by jakey200** [comment]
Will do
