### ISSUE TITLE
WIGG

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Navigation#1576]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 13 >

# References: (Official sources/charts)

< https://aimindonesia.dephub.go.id/images/eaip/521-WIGG%20AD%202.24-11D%20AMDT%2041.pdf
 >

**Comment by Czechoslovaki** [comment]
#1620
