### ISSUE TITLE
WIJJ

### ISSUE THREAD

**Issue by vinoalviano1994** [InfiniteFlightAirportEditing/Navigation#1577]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 31 >

# References: (Official sources/charts)

< https://aimindonesia.dephub.go.id/images/541-WIJJ%20-%20SULTAN%20THAHA%20[AD2.24-11E].pdf
 >

**Comment by 2000rpm** [comment]
[WIGG ILS31 2019 JULY 26.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4774877/WIGG.ILS31.2019.JULY.26.pdf)

**Comment by 2000rpm** [comment]
[WIJJ ILS31 2019 JULY 26.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4774882/WIJJ.ILS31.2019.JULY.26.pdf)
