### ISSUE TITLE
ZLXN

### ISSUE THREAD

**Issue by Berlin-N** [InfiniteFlightAirportEditing/Navigation#1581]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 11/29 >

# References: (Official sources/charts)

< 
![ZLXNILS](https://user-images.githubusercontent.com/62970735/84671375-e197e600-af59-11ea-9562-cc8a3f26af4a.PNG)
 >

**Comment by 2000rpm** [comment]
[CHINA ZLXN ILS11.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4781264/CHINA.ZLXN.ILS11.pdf)
[CHINA ZLXN ILS29.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4781266/CHINA.ZLXN.ILS29.pdf)
