### ISSUE TITLE
VVNB

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1595]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 11R/29L >

# References: (Official sources/charts)

<
![1ED925CF-35BD-4403-A23E-6C4EE3D8D176](https://user-images.githubusercontent.com/43931356/85359492-91fc8000-b540-11ea-99cd-0447b90d5131.png)
 >

**Comment by Czechoslovaki** [comment]
Just to verify that both runways have ILS according to Jepp charts?

**Comment by IFUA2003** [comment]
Yes

**Comment by MajorTomMueller** [comment]
Airport is still a open issue in Airports database. That’s why I put it on Hold here @velocity23
