### ISSUE TITLE
VVCA

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1596]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 32 >

# References: (Official sources/charts)

< 
![4A84870F-570D-4D56-BD1E-8A6E04EBEDAE](https://user-images.githubusercontent.com/43931356/85359598-ea338200-b540-11ea-9dae-f324b564a829.png)
 >

**Comment by Czechoslovaki** [comment]
#1620

**Comment by Czechoslovaki** [comment]
#1620
