### ISSUE TITLE
VVDN

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1599]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 35L >

# References: (Official sources/charts)

< 
![F31E3E18-8A79-4AE8-BABC-3DFFE76B5550](https://user-images.githubusercontent.com/43931356/85360361-28ca3c00-b543-11ea-838d-67a8863fe256.jpeg)
 >

**Comment by zhf21** [comment]
ILS for RWY 35L/35R needs updating. I'll take care of it.

**Comment by zhf21** [comment]
file:///Users/zacharyfriedman/Downloads/VVDN_DAD.pdf
file:///Users/zacharyfriedman/Downloads/VVDN_IDR.pdf
