### ISSUE TITLE
VVCR

### ISSUE THREAD

**Issue by IFUA2003** [InfiniteFlightAirportEditing/Navigation#1600]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< 02L and 02R/20L>

# References: (Official sources/charts)

< 
![72804B3B-ADA9-4390-91D4-1DD831D621FA](https://user-images.githubusercontent.com/43931356/96948160-2e468b80-150f-11eb-96a0-69375c5a1d25.jpeg)
![F1F18314-D541-413C-BD70-F42FA21EC2BF](https://user-images.githubusercontent.com/43931356/96948170-33a3d600-150f-11eb-8899-c32fb51268c3.jpeg)
![D5CDDC6E-5A8E-4228-B89D-631CF758275C](https://user-images.githubusercontent.com/43931356/96948176-36063000-150f-11eb-9eef-f6f9c34f0ee1.jpeg)

 >

**Comment by brennanhackard** [comment]
Has this airport passed OR yet? The latest version in the repo is from two years ago.

**Comment by AnthonyCK** [comment]
This is a duplicate issue. Already done #1468

**Comment by IFUA2003** [comment]
This airport has passed the OR

**Comment by jakey200** [comment]
It has not. It still shows the old version in the repo, so I cannot fix this issue.

**Comment by IFUA2003** [comment]
![0251D38A-0671-4CEB-8F62-53D7E7276A44](https://user-images.githubusercontent.com/43931356/96948086-ffc8b080-150e-11eb-9293-09b548580cc7.jpeg)
![Uploading F728A254-9A83-47B3-A073-4AD7E8D8253B.jpeg…]()

**Comment by Czechoslovaki** [comment]
ILS already fixed.

**Comment by IFUA2003** [comment]
Yes but we have another runway

**Comment by Czechoslovaki** [comment]
I also fixed that one too.

**Comment by IFUA2003** [comment]
I have just updated my issue, please check again. 02L, 20L/02R

**Comment by IFUA2003** [comment]
Oh thanks!
