### ISSUE TITLE
SBFL

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#1623]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Runway 14 length modified>

# Runway(s) with ILS: (If any)

< 14 >

# References: (Official sources/charts)

< http://ais.decea.gov.br/download/?arquivo=9cf0c1ec-571e-45e9-952f2ac2c8c9b1ad&apikey=1587263166 >

**Comment by Czechoslovaki** [comment]
#1620
