### ISSUE TITLE
UKBB

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1634]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

RWY 18s and 36s

# References: (Official sources/charts)

https://drive.google.com/file/d/1q1ZSYGS90bLngmfb3YygEdtlXbacEUkg/view?usp=sharing

**Comment by MBeringuy** [comment]
#1633

**Comment by MajorTomMueller** [comment]
UKBB had a navigation issue before. @ItsW1ll do we reopen issues here as well, or do we make new ones every time something changes? I have no clue.

**Comment by MajorTomMueller** [comment]
Duplicates #206
