### ISSUE TITLE
RPVM

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Navigation#1667]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

04/22

# References: (Official sources/charts)

http://sharepoint.aag.ph/portal/Downloads/Terminal%20Charts/RPVM.pdf

**Comment by Czechoslovaki** [comment]
@OscarConklin seems that RPVM doesn't have any ILS approaches. Even your source doesn't have any ILS stuff.

**Comment by OscarConklin** [comment]
Hmm that's strange it currently has ILS in Infinite Flight. My bad.

**Comment by brennanhackard** [comment]
@OscarConklin I'll delete them shortly.

**Comment by OscarConklin** [comment]
Thanks!

**Comment by AleksanderIF** [comment]
![RPVM ILS](https://user-images.githubusercontent.com/53284798/128354580-64d07381-b99e-45e6-b3ee-8734bfb17b41.png)
