### ISSUE TITLE
OERB

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1691]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

Rwy 33

# References: (Official sources/charts)

![ILS RWY 33](https://user-images.githubusercontent.com/32115399/93370917-ebb2d480-f827-11ea-9bfd-1fffc4e099d3.jpg)
https://www.airmate.aero/?page=airport_page&mode=search&lang=en&find=oerb&search_airport_submit=+

**Comment by Velocity23** [comment]
Updated in latest push
