### ISSUE TITLE
VELP

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1739]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
17
# References: (Official sources/charts)
https://aim-india.aai.aero/eaip-v2-01-2020/index-en-GB.html

**Comment by ShaneAviation** [comment]
The nav edit is currently not present in-app and is incorrectly placed within the glideslope.json and loc.json. I'll remove the colons after the ICAOs in each since that seems to be the source of the issue and rearrange the placement of the edit if that's alright.
