### ISSUE TITLE
UHSS

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#180]
Need to adjust ILS Approach for runway

**Comment by henrikbg** [comment]
No ILS for this airport.

**Comment by AleksanderIF** [comment]
ILS 01/19 charts: http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uhss/1-ad2-rus-uhss-097.pdf http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uhss/1-ad2-rus-uhss-098.pdf

**Comment by AleksanderIF** [comment]
Can supervisor open this issue?

**Comment by AleksanderIF** [comment]
I'll fix ILS later
