### ISSUE TITLE
EFMA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1801]
# Runway(s) with ILS: (If any)
< 21 >
# References: (Official sources/charts)
< https://vau.aero/navdb/chart/EFMA.pdf >

**Comment by MajorTomMueller** [comment]
vau.aero is not a source of first choice. Finnland eAIP is public available, even without registration. Please use the SOURCE of information, not a Repetitor where ever available.
https://ais.fi/ais/eaip/en/
