### ISSUE TITLE
EEKE

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1803]
# Runway(s) with ILS: (If any)
< 17 >
# References: (Official sources/charts)
< https://vau.aero/navdb/chart/EEKE.pdf >

**Comment by MajorTomMueller** [comment]
vau.aero is not a source of first choice. Estonia eAIP is public available, even without registration. Please use the SOURCE of information, not a Repetitor where ever available.
https://aim.eans.ee/en/eaip
