### ISSUE TITLE
FCBB

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Navigation#1804]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS/Localizer
# Runway(s) with ILS: (If any)
05 (ILS) / 23 (LOC)
# References: (Official sources/charts)
https://ais.asecna.aero/pdf/atlas/congo/brazzaville/pdf/brazzaville-01.pdf

**Comment by AleksanderIF** [comment]
will do this

**Comment by MajorTomMueller** [comment]
@GBKarp please put in here a recent reference for what you think needs to be changed. The one linked above is not available anymore.

**Comment by MajorTomMueller** [comment]
@GBKarp the "on Hold" label will be removed when you have referenced.

**Comment by GBKarp** [comment]
![image](https://user-images.githubusercontent.com/66634284/119263385-3950bf80-bbb5-11eb-86ca-8b3a485c429a.png)

There is no LOC or ILS on runway 23. I got confused when I first created the issue. I just want to remove it.

**Comment by MajorTomMueller** [comment]
A screenshot of a list of documents is not really a reference.
In addition I tried to explain you before that searching up procedures to find data for a LOC or GS is kind of last resort. The better way is to look in the text section of a airports AIP for the radio navigation aids list. It provides all data required.
Best is to reference this document, or a screenshot of the section in here. Your list shows just that you have found access to the relevant document but have no clue what to do with it properly. 
Here comes the hint: while you show a list of ICAO conformal documents you are looking for
AD 2.19  RADIO NAVIGATION AND LANDING AIDS
Go find! And then reference useful.

**Comment by GBKarp** [comment]
https://aim.asecna.aero/html/eAIP/FR-_05AD-2.FCBB-fr-FR.html#FCBB-AD-2.19
![image](https://user-images.githubusercontent.com/66634284/119264784-dfeb8f00-bbba-11eb-9dd3-7e60e224463c.png)
