### ISSUE TITLE
UHWW

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#181]
Need to adjust ILS Approach for runway

**Comment by henrikbg** [comment]
Which runway needs ILS? It seems there's an ILS in the files for a closed runway.

**Comment by sentikum** [comment]
16L-34R

**Comment by sentikum** [comment]
Sorry, 07L-25R.
South runway

**Comment by henrikbg** [comment]
07L/25R isn't in the WED file.

**Comment by sentikum** [comment]
07R-25L
![image](https://cloud.githubusercontent.com/assets/20271881/19840650/938e84e0-9f46-11e6-8f57-b0fd1774a828.png)

**Comment by henrikbg** [comment]
There is no ILS for 07R or 25L. In the file, there's an ILS for 25R.

**Comment by sentikum** [comment]
Please, do for 25R

**Comment by sentikum** [comment]
Check this
https://files.ivaoru.org/charts/uhww.pdf

**Comment by henrikbg** [comment]
I have no clue what anything says, everything is in Russian.

**Comment by sentikum** [comment]
Ok,

**Comment by NickArt1342** [comment]
Welp, the only up to date chart was in russian, I think I got everthing right though

**Comment by ItsW1ll** [comment]
Runway is 25R in LOC.json?

**Comment by ItsW1ll** [comment]
fixed in 41b515b
