### ISSUE TITLE
LPPD

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#1825]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
Rwy 30
# References: (Official sources/charts)
![LPPD_ils_rwy30](https://user-images.githubusercontent.com/32115399/101647975-1e7bfb80-3a18-11eb-8c43-578925c3d244.jpg)

**Comment by GBKarp** [comment]
I'll do this one

**Comment by GBKarp** [comment]
fix #1826
