### ISSUE TITLE
WATT

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Navigation#1848]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
< Instrument Landing Systems (ILS) >
# Runway(s) with ILS: (If any)
< Runway 25 With ILS >
# References: (Official sources/charts)
< Based Information from friend >

**Comment by AleksanderIF** [comment]
Yes, the best official source

**Comment by MBeringuy** [comment]
I'll do it.

**Comment by adibyaputra** [comment]
Thank you :)

Pada tanggal Sen, 28 Des 2020 22.17, Mauricio Beringuy <
notifications@github.com> menulis:
