### ISSUE TITLE
WAUU

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Navigation#1849]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
< Instrument Landing Systems (ILS) >
# Runway(s) with ILS: (If any)
< Runway 36 with ILS >
# References: (Official sources/charts)
< Based Information from friend >

**Comment by MBeringuy** [comment]
A friend's information is not official information. Please, it is necessary that you provide a link from an official source that provides us with an IAC chart of the airport in question.

**Comment by adibyaputra** [comment]
Thank you for your suggest :D

Pada tanggal Sen, 28 Des 2020 22.04, Mauricio Beringuy <
notifications@github.com> menulis:

**Comment by velocity23** [comment]
Airport does not have ILS according to Navigraph. If you find an official source that suggests otherwise we'll reopen this.
