### ISSUE TITLE
UKDE

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1853]
# Runway(s) with ILS: (If any)
< 20 >
# References: (Official sources/charts)
< https://vau.aero/navdb/chart/UKDE.pdf >

**Comment by liamkirky** [comment]
20 only has ILS.

**Comment by AleksanderIF** [comment]
Can you send me the official charts, I'll take a look. I found only vau.aero

**Comment by liamkirky** [comment]
![image](https://user-images.githubusercontent.com/19878689/102783253-904a3280-4392-11eb-8708-9c69d788d426.png)

**Comment by liamkirky** [comment]
![image](https://user-images.githubusercontent.com/19878689/102783293-99d39a80-4392-11eb-8f25-f9e69bc5a989.png)

**Comment by AleksanderIF** [comment]
Thanks
