### ISSUE TITLE
USSS

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#186]
Need to adjust ILS Approach for runways

**Comment by henrikbg** [comment]
Updated in 5bf135f.

**Comment by AleksanderIF** [comment]
small changes are needed:
Elevation is 766 ft
ILS 08R is CAT II now
http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/usss/1-ad2-rus-usss-txt.pdf
