### ISSUE TITLE
DAON

### ISSUE THREAD

**Issue by falous** [InfiniteFlightAirportEditing/Navigation#1869]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
< Enter text here > ILS
# Runway(s) with ILS: (If any)
< Enter text here >25
# References: (Official sources/
  https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAON/IAC3.pdf
< Enter text here >

**Comment by Czechoslovaki** [comment]
The nav issue is to be created **after** the airport has been accepted into the repo.

**Comment by falous** [comment]
hello this good ila accepts airport please you or do not forget add THEY thank you boucau

**Comment by Czechoslovaki** [comment]
The ILS has been fixed.
