### ISSUE TITLE
UWKD

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#187]
Need to adjust ILS Approach

**Comment by henrikbg** [comment]
This airport doesn't have an ILS.

**Comment by AleksanderIF** [comment]
ILS 11/29 http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uwkd/1-ad2-rus-uwkd-097.pdf http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uwkd/1-ad2-rus-uwkd-098.pdf
