### ISSUE TITLE
KVGT

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1882]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
12L
# References: (Official sources/charts)
Z

**Comment by zhf21** [comment]
ILS needs an update; airport was redone after this issue was created. I'll take care of it.

**Comment by zhf21** [comment]
https://aeronav.faa.gov/d-tpp/2103/06970IL12L.PDF
