### ISSUE TITLE
KNFW

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#1903]
# Runway(s) with ILS: (If any)
18/36
# References: (Official sources/charts)
http://airnav.com/airport/KNFW

**Comment by MajorTomMueller** [comment]
best source for US:

https://www.faa.gov/air_traffic/flight_info/aeronav/aero_data/Airport_Data/

https://nfdc.faa.gov/nfdcApps/services/ajv5/airportDisplay.jsp?airportId=KNFW

https://nfdc.faa.gov/nfdcApps/services/ajv5/airportDisplay.jsp?airportId=KNFW
