### ISSUE TITLE
LECO

### ISSUE THREAD

**Issue by PaulNielsen** [InfiniteFlightAirportEditing/Navigation#191]
Runway moved during redo. ILS runway 21.

**Comment by dushyants19** [comment]
Fixed in 1026d52b8886d5bba4696193f376da05be971b33

**Comment by ItsW1ll** [comment]
ILS needs adding again.

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

21

# References:

Navigraph/Jeppesen
