### ISSUE TITLE
VVDH

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1910]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
29
# References: (Official sources/charts)

**Comment by IFUA2003** [comment]
![403F2BC4-25EA-4BB5-9742-AAB07F4B009B](https://user-images.githubusercontent.com/43931356/104125696-fa9b3500-538a-11eb-81c5-953a2f287b2c.jpeg)
