### ISSUE TITLE
OJAI

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#1931]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
08L/26R  |  26L
# References: (Official sources/charts)

![image](https://user-images.githubusercontent.com/51279558/104786222-35adb780-5741-11eb-8dd8-93e3ff1a3434.png)
![image](https://user-images.githubusercontent.com/51279558/104786228-39d9d500-5741-11eb-9796-c7ce13944bc1.png)
![image](https://user-images.githubusercontent.com/51279558/104786237-3e05f280-5741-11eb-801c-e7966ce6c959.png)

**Comment by MajorTomMueller** [comment]
As far as I can see there has nothing changed. All three runways have ILS with correct identification and frequency already.
What needs to be done then?
