### ISSUE TITLE
EDDC

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#195]
The runway was slightly moved to fit the imagery and to reach the same length as it is shown in the airport chart

**Comment by IceBlue02** [comment]
Waiting for approval- @dushyants19 sort it. Will do then

**Comment by henrikbg** [comment]
Has this been approved?

**Comment by moritzbabl** [comment]
Should be approved, yes

**Comment by IceBlue02** [comment]
In which case @dushyants19 must have not committed it- https://github.com/InfiniteFlightAirportEditing/Airports/blob/master/Germany/EDDC/apt.dat

[code] 1000 Generated by Infinite Flight Airport Editing (World Parser)/AB [/code

**Comment by dushyants19** [comment]
Check August 2016 @iceblue02

**Comment by NickArt1342** [comment]
@IceBlue02 I didn't realize this was assigned to you and just did it, I hope you don't mind
