### ISSUE TITLE
KALB

### ISSUE THREAD

**Issue by ECoops-123** [InfiniteFlightAirportEditing/Navigation#1954]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS
# Runway(s) with ILS: (If any)
01, 19
# References: (Official sources/charts)

http://aeronav.faa.gov/d-tpp/2014/00010IL1.PDF

http://aeronav.faa.gov/d-tpp/2014/00010IL19.PDF

**Comment by GBKarp** [comment]
#287 🤦
