### ISSUE TITLE
ENNA

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Navigation#1964]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
ILS/LOC
# Runway(s) with ILS: (If any)
16 (LOC)/ 34 (ILS)
# References: (Official sources/charts)
Jeppensen

**Comment by MajorTomMueller** [comment]
Top reference. Everybody can open it.
Sorry, but that is not what I call a reference. At least you could make a screenshot of the relevant page and past in here.
Beside that Jeppesen is not the best reference where public payfree sources are available.
For Norway this is Avinor, the host of official Norwegian eAIP.
I know you could do better @GBKarp , please do.

**Comment by GBKarp** [comment]
[ILS34.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5880523/ILS34.pdf)
[LOC16.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5880524/LOC16.pdf)
