### ISSUE TITLE
UUWW

### ISSUE THREAD

**Issue by sentikum** [InfiniteFlightAirportEditing/Navigation#197]
Need to adjust ILS approach

**Comment by henrikbg** [comment]
Has this been committed to the repository? Looks like an X-Plane vintage airport when I open it up in WED.

**Comment by sentikum** [comment]
Updated.

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

06/24, 01/19

# References: 

http://opennav.com/pdf/UUWW/ad2-rus-uuww-098.pdf
http://opennav.com/pdf/UUWW/ad2-rus-uuww-097.pdf
http://opennav.com/pdf/UUWW/ad2-rus-uuww-099.pdf
http://opennav.com/pdf/UUWW/ad2-rus-uuww-100.pdf

**Comment by AleksanderIF** [comment]
Airport reworked
http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uuww/1-ad2-rus-uuww-097.pdf
http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uuww/1-ad2-rus-uuww-098.pdf
http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uuww/1-ad2-rus-uuww-099.pdf
http://www.caiga.ru/common/AirInter/validaip/aip/ad/ad2/rus/uuww/1-ad2-rus-uuww-100.pdf
