### ISSUE TITLE
KFUL

### ISSUE THREAD

**Issue by falous** [InfiniteFlightAirportEditing/Navigation#1977]
# Summary of Navigation issue: (ILS, Waypoints, etc.)
< Enter text here >ILS
# Runway(s) with ILS: (If any)
< Enter text here >25L
# References: (Official sources/charts)
< Enter text here >
https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAOO/IAC5.pdf

**Comment by Czechoslovaki** [comment]
Duplicate issue (#1496), ILS has been edited in #1962)

**Comment by falous** [comment]
hello yes it is 25R its 25L it is not the same thank you

Envoyé de mon iPad

Le 28 janv. 2021 à 22:50, Claudio <notifications@github.com> a écrit :

﻿

Duplicate issue (#1496<https://github.com/InfiniteFlightAirportEditing/Navigation/issues/1496>), ILS has been edited in #1962<https://github.com/InfiniteFlightAirportEditing/Navigation/pull/1962>)

**Comment by falous** [comment]
Hello

there are two Ils  thanks

Envoyé de mon iPad

Le 28 janv. 2021 à 22:57, zazo zazo <tonytoca@live.fr> a écrit :

﻿ hello yes it is 25R its 25L it is not the same thank you

Envoyé de mon iPad

Le 28 janv. 2021 à 22:50, Claudio <notifications@github.com> a écrit :

﻿

Duplicate issue (#1496<https://github.com/InfiniteFlightAirportEditing/Navigation/issues/1496>), ILS has been edited in #1962<https://github.com/InfiniteFlightAirportEditing/Navigation/pull/1962>)

**Comment by falous** [comment]
DAOO

**Comment by velocity23** [comment]
Duplicate, I'll reopen the other one for you.
