### ISSUE TITLE
DAOI

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Navigation#1984]
# Airport ICAO
Enter text here
DAOI
# Runway(s) with ILS
Enter text here LOC 26
# References (Official sources/charts)
Enter text here. Graphique Jeppesen
<img width="481" alt="Loc daoi" src="https://user-images.githubusercontent.com/63318768/106320358-10f22d80-6273-11eb-9440-00f1b2832110.png">

# Are you working on this?

Yes/No

**Comment by Czechoslovaki** [comment]
A VOR/DME approach is not ILS or LOC.
