### ISSUE TITLE
DAUA

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Navigation#1989]
# Airport ICAO
Enter text hère
ILS
# Runway(s) with ILS
Enter text here 04
# References (Official sources/charts)
Enter text here

Graphique Jeppesen

<img width="487" alt="Image PNG" src="https://user-images.githubusercontent.com/63318768/106516458-5878f380-64d7-11eb-8bb8-c78416fa2c77.png">

# Are you working on this?

Yes/No

**Comment by GBKarp** [comment]
I'm doing it

**Comment by brennanhackard** [comment]
DAUA hasn’t been edited yet. ILS will not be aligned until it is.

**Comment by tonyi31** [comment]
> je le fait
thank you
