### ISSUE TITLE
DAAT

### ISSUE THREAD

**Issue by tonyi31** [InfiniteFlightAirportEditing/Navigation#1991]
# Airport ICAO
DAAT
# Runway(s) with ILS
08/ 20
# References (Official sources/charts)
<img width="478" alt="Ils20" src="https://user-images.githubusercontent.com/63318768/106523453-6e8bb180-64e1-11eb-9d85-a3d4a9397204.png">
<img width="508" alt="Ils08" src="https://user-images.githubusercontent.com/63318768/106523457-70ee0b80-64e1-11eb-9cdf-686a56b331b0.png">
Graphique Jeppesen

# Are you working on this?

Yes

**Comment by brennanhackard** [comment]
@tonyi31 please refrain from making nav issues for airports until the airport has been added to the repository.

**Comment by tonyi31** [comment]
airport island already exists on if

**Comment by velocity23** [comment]
The airport does already exist @brennanhackard.

@tonyi31 Please remember to fill out the new "are you working on this" field found below the charts so that we know whether you're working on the issue or if it's up for one of us to take.

**Comment by MBeringuy** [comment]
The airport exists in the airport repository, but it is a generic edition; it needs to be reissued from scratch before this navigation issue is done.

**Comment by Czechoslovaki** [comment]
I'll do this.
