### ISSUE TITLE
CYUL

### ISSUE THREAD

**Issue by velocity23** [InfiniteFlightAirportEditing/Navigation#1996]
# Airport ICAO
CYUL

# Runway(s) with ILS
06L, 06R, 10, 24L, 24R

# References (Official sources/charts)
https://vau.aero/navdb/chart/CYUL.pdf

# Are you working on this?

Yes

**Comment by MBeringuy** [comment]
I'll do it.

**Comment by zhf21** [comment]
No proof of existence for ILS RWY 10.

<img width="1440" alt="Screen Shot 2021-09-30 at 10 02 10 AM" src="https://user-images.githubusercontent.com/67797012/135470002-8daf7a17-e2b5-4032-97d1-ee2803a5d81b.png">
