### ISSUE TITLE
SKBO

### ISSUE THREAD

**Issue by velocity23** [InfiniteFlightAirportEditing/Navigation#1997]
# Airport ICAO
SKBO

# Runway(s) with ILS
13L, 13R

# References (Official sources/charts)

https://vau.aero/navdb/chart/SKBO.pdf

# Are you working on this?

Yes

**Comment by zhf21** [comment]
ILS category fixes.

<img width="407" alt="Screen Shot 2021-09-30 at 7 35 24 PM" src="https://user-images.githubusercontent.com/67797012/135544484-864eb33c-b7e0-4881-90c1-63150e4ab306.png">

<img width="408" alt="Screen Shot 2021-09-30 at 7 35 52 PM" src="https://user-images.githubusercontent.com/67797012/135544504-006fdcde-646a-42af-8902-29730fb1180c.png">
