### ISSUE TITLE
LIRF

### ISSUE THREAD

**Issue by velocity23** [InfiniteFlightAirportEditing/Navigation#1998]
# Airport ICAO
LIRF

# Runway(s) with ILS
16L, 16R, 25, 34L, 34R

# References (Official sources/charts)
https://vau.aero/navdb/chart/LIRF.pdf

# Are you working on this?

No

**Comment by MajorTomMueller** [comment]
Again, official sources (free of charge) are preferred:
[LI_AD_2_LIRF_en_2020-12-31.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5963448/LI_AD_2_LIRF_en_2020-12-31.pdf)

**Comment by velocity23** [comment]
Now up for grabs, short on time rn

**Comment by velocity23** [comment]
@MajorTomMueller Why have I been re-assigned?

**Comment by MajorTomMueller** [comment]
Overlapped, sorry
