### ISSUE TITLE
RJCC

### ISSUE THREAD

**Issue by velocity23** [InfiniteFlightAirportEditing/Navigation#1999]
# Airport ICAO
RJCC

# Runway(s) with ILS
01L, 01R, 19L, 19R

# References (Official sources/charts)
https://vau.aero/navdb/chart/RJCC.pdf

# Are you working on this?
No

**Comment by MajorTomMueller** [comment]
VAU.aero is outdated.
Do not use outdated hobbyists sources where official recent sources are available:
[JP-AD-2-RJCC-en-JP.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5963444/JP-AD-2-RJCC-en-JP.pdf)

**Comment by velocity23** [comment]
This one is up for grabs too, super busy atm

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Navigation/commit/94b8c5491355a4df2223ba59eba003270bcf3a14
