### ISSUE TITLE
EGMC

### ISSUE THREAD

**Issue by jpperks** [InfiniteFlightAirportEditing/Navigation#20]
Runway 06 needs an ILS... Same frequency as runway 24.

**Comment by jpperks** [comment]
Runway length has been changed to adopt the re-development of the airport.

**Comment by DavidCutler** [comment]
Is it missing fixes on approach? The ILS should already be fixed.

**Comment by Will171** [comment]
have the runway numbers been changed to 05-23?

**Comment by Will171** [comment]
okay, i have done that on wed, just wanted to know if it was updated in the nav section

**Comment by ItsW1ll** [comment]
Runways further moved in recent update
