### ISSUE TITLE
ETAR

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#201]
Runways were moved during editing, airport is added

**Comment by henrikbg** [comment]
Updated in ea089cf.

**Comment by zhf21** [comment]
RWY 08 and 26 need to be added to the LOC.json file and adjusted in the Glisdeslope.json file. RWY 09 and 27 need to be added to the Glideslope.json file and adjusted in the LOC.json file. 

I will be making these additions/fixes.

**Comment by zhf21** [comment]
**RWY 08:**

 <img width="1440" alt="Screen Shot 2021-05-24 at 9 49 19 AM" src="https://user-images.githubusercontent.com/67797012/119357228-50ef7d00-bc75-11eb-8efc-f5a22b769308.png">

**RWY 09:**

<img width="1440" alt="Screen Shot 2021-05-24 at 9 49 57 AM" src="https://user-images.githubusercontent.com/67797012/119357315-682e6a80-bc75-11eb-9239-7802f3280938.png">

**RWY 26:** 

<img width="1440" alt="Screen Shot 2021-05-24 at 9 49 35 AM" src="https://user-images.githubusercontent.com/67797012/119357256-5b117b80-bc75-11eb-9891-7a05d15f0352.png">

**RWY 27:** 

<img width="1440" alt="Screen Shot 2021-05-24 at 9 50 11 AM" src="https://user-images.githubusercontent.com/67797012/119357342-6fee0f00-bc75-11eb-9694-af1b980f66be.png">
