### ISSUE TITLE
LEAM

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#202]
Runway Moved

**Comment by ItsW1ll** [comment]
Issue recycled as it was a duplicate ♻️

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

31
13 (LOC)

# References: 

https://ais.enaire.es/AIP/AIPS/AMDT_302_2018_AIRAC_05_2018/AIP.html (pages 167-169)

**Comment by ItsW1ll** [comment]
Runway was not changed!
