### ISSUE TITLE
EDVK

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#204]
The airport in the new file was opened some years ago, the old airport was deleted, the new runway is equipped with ILS and was only displayed as a gravel runway representing the construction site, so it probably doesn't have an ILS yet.

The airport should be added shortly

**Comment by Will171** [comment]
use google earth imagery

**Comment by moritzbabl** [comment]
I did, the new airport is done and the old removed, sorry I forgot to add that in the initial post

**Comment by moritzbabl** [comment]
airport slightly moved

**Comment by ItsW1ll** [comment]
Do all runways have ils?

**Comment by moritzbabl** [comment]
fixed again after duplicate removal
