### ISSUE TITLE
LECO

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Navigation#2067]
# Airport ICAO
LECO

# Runway(s) with ILS
RWY21

# References (Official sources/charts)
![image](https://user-images.githubusercontent.com/76137019/108931234-ec3c6c00-760c-11eb-9540-a05571bfd55e.png)

# Are you working on this?

No, just reporting the changes.

**Comment by MBeringuy** [comment]
I'll do it.
