### ISSUE TITLE
UAOO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2076]
# Airport ICAO
UAOO
# Runway(s) with ILS
05
# References (Official sources/charts)

# Are you working on this?
Yes

**Comment by MajorTomMueller** [comment]
What was the change and what is the source?

**Comment by Czechoslovaki** [comment]
The ILS for this airport did not exist previously.
https://www.ans.kz/AIP/eAIP/2021-02-25-AIRAC/html/index-en-GB.html
