### ISSUE TITLE
NZCH

### ISSUE THREAD

**Issue by lachieee** [InfiniteFlightAirportEditing/Navigation#208]
(Main) Runway 02/20 has a Cat II ILS System. _No ILS on secondary runway 11/29 or 02L/20R grass strip._ 

Have made runway alignments during editing - ILS approach will need to be adjusted.

**Comment by IceBlue02** [comment]
Done
https://github.com/InfiniteFlightAirportEditing/Navigation/commit/1f907b9a3b51a6f5ba1f9a36b330b2b069116d67
