### ISSUE TITLE
OLBA

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2086]
# Airport ICAO
OLBA
# Runway(s) with ILS
03, 16, 17
# References (Official sources/charts)

# Are you working on this?
Yes

**Comment by MajorTomMueller** [comment]
Reference is missing

**Comment by MajorTomMueller** [comment]
![65785578-BB68-4673-BA1F-1C6366084B7D](https://user-images.githubusercontent.com/26853210/110231434-ff5a1080-7f17-11eb-9a25-d70b29fe27bd.jpeg)
![083B446F-D068-456F-B657-DE757C06C00F](https://user-images.githubusercontent.com/26853210/110231435-02550100-7f18-11eb-8d93-007ae8dcbef5.jpeg)
![8EAB6F8D-8012-4F55-B1E3-2CD5EB14015C](https://user-images.githubusercontent.com/26853210/110231439-03862e00-7f18-11eb-91cd-b5be1e42d3d5.jpeg)
