### ISSUE TITLE
KTPA

### ISSUE THREAD

**Issue by AleksanderIF** [InfiniteFlightAirportEditing/Navigation#2089]
# Airport ICAO
KTPA

# Runway(s) with ILS
1R - LOC is missing
# References (Official sources/charts)
https://www.faa.gov/aero_docs/dtpp/2102/00416L1R.PDF#nameddest=(TPA)

# Are you working on this?
Yes

**Comment by zhf21** [comment]
A minor altitude adjustment and movement of the code for the 1R LOC will be done.
