### ISSUE TITLE
WIMM

### ISSUE THREAD

**Issue by 4riw** [InfiniteFlightAirportEditing/Navigation#209]
WIMM, Medan Kualanamu, Sumatera Utara, Indonesia (new airport, old WIMM (Medan Polonia) now become WIMK, an airforce base)
*adding 2 new ILS for runway 05/23 (IDES & IDEL), removed ILS from old WIMM (IMDN)
*adding VOR SERDANG (DES)

**Comment by jakey200** [comment]
Fixed in #1503
