### ISSUE TITLE
ENSO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2091]
# Airport ICAO
ENSO
# Runway(s) with LOC
14
# References (Official sources/charts)

# Are you working on this?
Yes

**Comment by MajorTomMueller** [comment]
Reference is missing again @Czechoslovaki

**Comment by MajorTomMueller** [comment]
![BCAE5401-BB38-4E16-98F1-6BA3F5C2E6D9](https://user-images.githubusercontent.com/26853210/110231316-60cdaf80-7f17-11eb-8645-4ba65bcc2f09.jpeg)
