### ISSUE TITLE
LEVD

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Navigation#2095]
# Airport ICAO
LEVD
# Runway(s) with ILS
23
# References (Official sources/charts)
![Screenshot (146)](https://user-images.githubusercontent.com/76137019/110227183-4960d900-7ebb-11eb-92fb-332d9fd3de9f.png)

# Are you working on this?

No, just reporting the changes

**Comment by MajorTomMueller** [comment]
So that I didn’t need to search: what changed @brunocr1050 ?
Runway numbers, identifiers, or frequencies?

**Comment by MajorTomMueller** [comment]
![719193F0-ED48-49B6-A2DE-C8120D67BDCE](https://user-images.githubusercontent.com/26853210/110231290-1ba97d80-7f17-11eb-8035-7b9e67e4e553.jpeg)
