### ISSUE TITLE
CYXD

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#21]
Recycled ♻️
 
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

34 Misaligned

# References: (Official sources/charts)

Name: GS, Identifier: IXD with true heading 180.0° is 180° off of airport CYXD's runway 34 true heading of 0.0°.

**Comment by RyanEpps** [comment]
Airport needs redone first. Invalid.
