### ISSUE TITLE
KGRB

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Navigation#2145]
# Airport ICAO
KGRB

# Runway(s) with ILS
ILS - 6, 36

# References (Official sources/charts)
ILS 6 - https://aeronav.faa.gov/d-tpp/2102/00873IL6.PDF
ILS 36 - https://aeronav.faa.gov/d-tpp/2102/00873IL36.PDF

# Are you working on this?

No

**Comment by MajorTomMueller** [comment]
The LOC BC is just a procedure of the ILS of the opposite direction. It is NOT added to this database, and there is no need to do so.
