### ISSUE TITLE
VAPO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2170]
# Airport ICAO
VAPO
# Runway(s) with ILS
28
# References (Official sources/charts)

# Are you working on this?
Yes

**Comment by MajorTomMueller** [comment]
Reference missing ... 😉

**Comment by Czechoslovaki** [comment]
![image](https://user-images.githubusercontent.com/51279558/112038240-d59c0e80-8aff-11eb-91ae-5b9d375cae1a.png)
