### ISSUE TITLE
UMIO

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2188]
# Airport ICAO
UMIO
# Runway(s) with ILS
05/23
# References (Official sources/charts)
![image](https://user-images.githubusercontent.com/51279558/112728871-921e1780-8ee6-11eb-98c1-79f8ed3de801.png)
![image](https://user-images.githubusercontent.com/51279558/112728873-95190800-8ee6-11eb-84f7-f8bb34b10eb5.png)

# Are you working on this?
Yes

**Comment by zhf21** [comment]
RWY 05 is a CAT-II.

<img width="428" alt="Screen Shot 2021-09-26 at 11 11 18 PM" src="https://user-images.githubusercontent.com/67797012/134840068-188310b7-98b5-4df2-b7f9-4cf9e57e98a1.png">
