### ISSUE TITLE
EGPB STAR's and SID's

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#22]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

New RNAV approach 

# References: (Official sources/charts)

http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=141&Itemid=190.html

**Comment by HenrikBerg02** [comment]
Strange... I can't seem to find YGDO in either the LOC.json and Glideslope.json file. Not sure how to fix this one to be honest.

**Comment by dushyants19** [comment]
Fixed, issue in the Runway part
