### ISSUE TITLE
ENFL

### ISSUE THREAD

**Issue by Czechoslovaki** [InfiniteFlightAirportEditing/Navigation#2205]
# Airport ICAO
ENFL
# Runway(s) with ILS
07 (LOC)
# References (Official sources/charts)
![image](https://user-images.githubusercontent.com/51279558/113381513-fd774780-9333-11eb-9892-a585b4b977b4.png)
# Are you working on this?
Yes

**Comment by Daniboi737** [comment]
Why did you open this? I were about to do it as I saw this airport I did was aprroved

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/6773

**Comment by Daniboi737** [comment]
Anyway, then I don’t have to do something about making sure the ILS Get updated?
