### ISSUE TITLE
KPBI STARS / Trump Controversy

### ISSUE THREAD

**Issue by carmichaelalonso** [InfiniteFlightAirportEditing/Navigation#223]
Because 'murica:
http://www.palmbeachpost.com/news/local/faa-navigational-coordinates-longer-honor-trump/ODYSsDRzNK5NR8i0DXBaGN/

Updated chart:
[00449IL28R.PDF](https://github.com/InfiniteFlightAirportEditing/Navigation/files/680237/00449IL28R.PDF)

Thanks to Tim for making this known to me.

**Comment by ItsW1ll** [comment]
what's the progress on this henrik?

**Comment by ItsW1ll** [comment]
Which fixes have been replaced by what names?

**Comment by ItsW1ll** [comment]
Issue finally fixed in 5af9bc4
