### ISSUE TITLE
KJVL

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Navigation#2250]
# Airport ICAO
KJVL

# Runway(s) with ILS
04, 32
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2103/00938IL4.PDF
https://aeronav.faa.gov/d-tpp/2103/00938IL32.PDF

# Are you working on this?

Yes

**Comment by zhf21** [comment]
Will complete when previous commits are merged.

**Comment by MajorTomMueller** [comment]
All your previous commits are merged.

**Comment by zhf21** [comment]
I didn't realize there was a previous issue for this airport. That's my bad. Can I use this issue for a new airport?

**Comment by zhf21** [comment]
Issue updated to KJVL.
