### ISSUE TITLE
BIEG

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Navigation#2279]
# Airport ICAO
BIEG

# Runway(s) with ILS
04
# References (Official sources/charts)
<img width="1024" alt="Screen Shot 2021-04-11 at 1 29 07 PM" src="https://user-images.githubusercontent.com/67797012/114314786-259c3e80-9aca-11eb-8eee-2ccdbe0544f9.png">

# Are you working on this?

Yes

**Comment by RyanEpps** [comment]
A-OK

**Comment by zhf21** [comment]
Appears as if the ILS was done without an issue. No changes needed.
