### ISSUE TITLE
EBAW

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Navigation#2283]
# Airport ICAO
EBAW

# Runway(s) with ILS
29
# References (Official sources/charts)
[EBAW_IAC01_v26.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/6292450/EBAW_IAC01_v26.pdf)

# Are you working on this?

Yes

**Comment by becarboner3000** [comment]
ILS will need adjusting after latest commit.

![Screenshot (9)](https://user-images.githubusercontent.com/76137019/123147479-b5dcf500-d424-11eb-8f3b-14db60febf3c.png)

**Comment by zhf21** [comment]
I'll fix. Was the new version commited yet? I do not see it in the repo.

**Comment by zhf21** [comment]
All fixed. Nice work on the airport, Bruno!
