### ISSUE TITLE
DAUB

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Navigation#2292]
# Airport ICAO
DAUB

# Runway(s) with ILS
31
# References (Official sources/charts)
![image0](https://user-images.githubusercontent.com/67797012/114335712-5d7fa200-9b1b-11eb-8f94-b32af70ad7a9.jpg)

# Are you working on this?

Yes

**Comment by MajorTomMueller** [comment]
What is this?
The airport was already edited? Why are you editing a random airports ILS?

**Comment by MajorTomMueller** [comment]
Your reference is not good as well!

https://www.sia-enna.dz/PDF/AIP/AD/AD2/DAUB/DAUB.pdf

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/4607

**Comment by zhf21** [comment]
Regardless of a previous issue, DAUB needed an ILS fix. The bearings weren’t correspondent to the apt.fat, nor was the GS frequency correct.
