### ISSUE TITLE
CYYC

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#230]
RWY 17L/35R was manually added by me. RWY 07/25, 17L/35R and 11/29 have been moved.

**Comment by moritzbabl** [comment]
added ILS for 11 17L and 35R, renamed 28 to 29, 34 to 35L and 16 to 17R, edited the identifiers

**Comment by ECoops-123** [comment]
Roses are red, violets are blue, I reworked this airport, so I'll sort this Nav issue too

http://imageserver.fltplan.com/merge/Canada/merge210422/Single/CYYC_ILS_RWY_17L.pdf?_ga=2.210491413.1294304998.1619820300-1883567863.1618518353

http://imageserver.fltplan.com/merge/Canada/merge210422/Single/CYYC_ILS_RWY_17R.pdf?_ga=2.210491413.1294304998.1619820300-1883567863.1618518353

http://imageserver.fltplan.com/merge/Canada/merge210422/Single/CYYC_ILS_RWY_29.pdf?_ga=2.210491413.1294304998.1619820300-1883567863.1618518353

http://imageserver.fltplan.com/merge/Canada/merge210422/Single/CYYC_ILS_RWY_35L.pdf?_ga=2.137786416.1294304998.1619820300-1883567863.1618518353

http://imageserver.fltplan.com/merge/Canada/merge210422/Single/CYYC_ILS_RWY_35R.pdf?_ga=2.137786416.1294304998.1619820300-1883567863.1618518353
