### ISSUE TITLE
CYYT

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#231]
ILS RWY 16/34, 11/29 have been moved.

**Comment by moritzbabl** [comment]
fixed

**Comment by zhf21** [comment]
RWY 11 ILS-cat-I -> ILS-cat-II + fixes.

<img width="402" alt="Screen Shot 2021-09-30 at 11 44 56 AM" src="https://user-images.githubusercontent.com/67797012/135487962-eafbc3fa-0135-4317-8ae9-7e43fa42a607.png">
