### ISSUE TITLE
KHYR

### ISSUE THREAD

**Issue by ShaneAviation** [InfiniteFlightAirportEditing/Navigation#2319]
# Airport ICAO
KHYR

# Runway(s) with ILS
21

# References (Official sources/charts)
* 21 - https://aeronav.faa.gov/d-tpp/2104/05411IL21.PDF

# Are you working on this?
Yes

**Comment by AleksanderIF** [comment]
need to remove duplicate ILS/LOC, I'll do it
![e14619f88095a2e2da3795da380ae8f8](https://user-images.githubusercontent.com/53284798/122090611-9cc6b980-ce10-11eb-831f-c12720af3167.png)
