### ISSUE TITLE
EDDB

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#232]
ILS RWY 07L/25R has been moved. ILS RWY 07R/25L has been manually added in by me.

**Comment by moritzbabl** [comment]
fixed and added the new ILSs, renamed 07/25 to 07L/25R

**Comment by moritzbabl** [comment]
fixed

**Comment by moritzbabl** [comment]
Adjustment for ILSs needed

**Comment by Czechoslovaki** [comment]
Any ILS on 07R / 25L?
