### ISSUE TITLE
KIAG

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Navigation#2330]
# Airport ICAO
KIAG
# Runway(s) with ILS
28R
# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2104/00614IYLY28R.PDF
# Are you working on this?
No
NOTAM for the person who edits this: The GS is 2.50°.

**Comment by zhf21** [comment]
I will do this. I will begin in ~10 mins.
