### ISSUE TITLE
LTFM Runway 36/18 ILS Adding

### ISSUE THREAD

**Issue by TurkishCptArda737** [InfiniteFlightAirportEditing/Navigation#2342]
# Airport ICAO
LTFM

# Runway(s) with ILS
Runway 36/18 ILS Intersections (waypoints) isn't available
# References (Official sources/charts)

https://www.simfeats.com/flight-simulator/airport-charts/ltfm-istanbul-airport/36152-lt-ad-2-ltfm-instrument-approach-chart-icao-iac-24-ils-y-cat-i-or-cat-ii-rwy-36

https://www.simfeats.com/flight-simulator/airport-charts/ltfm-istanbul-airport/36151-lt-ad-2-ltfm-instrument-approach-chart-icao-iac-23-ils-y-cat-i-or-cat-ii-rwy-18

# Are you working on this?

No

**Comment by AleksanderIF** [comment]
What needs to be changed? I looked through it and didn't see any errors. @TurkishCptArda737

**Comment by AleksanderIF** [comment]
#1126

**Comment by TurkishCptArda737** [comment]
> What needs to be changed? I looked through it and didn't see any errors. @TurkishCptArda737

The ILS Waypoints, SID and STARS, Intersections isnt available. Only the Approach path. And on the real it exist UHN (VOR) 109.85 on Approach. Also the Missed approach Fix "RIZKO" is missed.

**Comment by ECoops-123** [comment]
Runway already has ILS
![Screenshot_20210510-155124](https://user-images.githubusercontent.com/59462519/117679020-d409d100-b1a7-11eb-90d4-7ca5426a513b.jpg)


Fixes come with automatic third party sources that we do bit control. These come every year. Time will get these into the game, thanks. 👍

**Comment by TurkishCptArda737** [comment]
> Runway already has ILS
> ![Screenshot_20210510-155124](https://user-images.githubusercontent.com/59462519/117679020-d409d100-b1a7-11eb-90d4-7ca5426a513b.jpg)
> 
> 
> Fixes come with automatic third party sources that we do bit control. These come every year. Time will get these into the game, thanks. 👍
> 


But I mean, every month Infinite Flight team adds new Scenery updates. They can add this waypoints too. We can't use the Runway for now since it was added. It looks in the future we won't. Because we can't do a SID Departure, cause it isn't available. That look nosense. Maybe we can work it now and send next month as Scenery update?

**Comment by MajorTomMueller** [comment]
#1126 #7
and it is not oursanymore to edit waypoints.
Please do not spam our issue tracker.
