### ISSUE TITLE
KOFF

### ISSUE THREAD

**Issue by brunocr1050** [InfiniteFlightAirportEditing/Navigation#2344]
# Airport ICAO
KOFF

# Runway(s) with ILS
12/30

# References (Official sources/charts)
For runway 12: https://airportdocs.iflightplanner.com/2104/00544IL12.PDF
For runway 30: https://airportdocs.iflightplanner.com/2104/00544ILY30.PDF

# Are you working on this?
No

**Comment by ShaneAviation** [comment]
I can work on this one.
