### ISSUE TITLE
ZUKD

### ISSUE THREAD

**Issue by korgast** [InfiniteFlightAirportEditing/Navigation#2362]
# Airport ICAO
ZUKD

# Runway(s) with ILS
15
# References (Official sources/charts)
![7A3FF352-36C4-4230-9891-BD11111CF98C](https://user-images.githubusercontent.com/62528652/118404493-bb1c8680-b6a5-11eb-8e0d-11c65ff43f5a.jpeg)

# Are you working on this?
No

**Comment by zhf21** [comment]
I can do this.
