### ISSUE TITLE
LTFD

### ISSUE THREAD

**Issue by feitidede** [InfiniteFlightAirportEditing/Navigation#2366]
# Airport ICAO
LTFD
# Runway(s) with ILS
05
# References (Official sources/charts)
http://www.airmate.aero/php/pdf_viewer/web/viewer.php?pdf=LT/LTFD/400000000563403.pdf#page=1&zoom=auto,-14,848

# Are you working on this?

no

**Comment by zhf21** [comment]
I gotcha.
