### ISSUE TITLE
FWKI

### ISSUE THREAD

**Issue by GBKarp** [InfiniteFlightAirportEditing/Navigation#2383]
# Airport ICAO
FWKI
# ICAOs issue Number in Airport repository
https://github.com/InfiniteFlightAirportEditing/Airports/issues/4347
# Runway(s) with LOC/GS
14
# References (Official sources/charts)
[FWKI.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/6532551/FWKI.pdf)
# What needs to be done (new add, correction freq/ID/elev./...),
Currently only has a LOC, will add a GS because it's an ILS.
# Are you working on this?
Yes, once my current PR is merged.

**Comment by zhf21** [comment]
Mine.
