### ISSUE TITLE
PHNL

### ISSUE THREAD

**Issue by DavidCutler** [InfiniteFlightAirportEditing/Navigation#24]
Edit data for 26L

**Comment by carmichaelalonso** [comment]
This one doesn't need changing; it's an LDA, which is handled differently and not supported in IF.

**Comment by Swang007** [comment]
The problem with this is that anyone who tries to enable APPR on 26L will land somewhere in the terminals to the north. Should it just be removed and treated as a GPS approach @carmichaelalonso?

**Comment by carmichaelalonso** [comment]
It's an LDA, which is handled differently and not supported in IF. Nothing should be done to this.

**Comment by jakey20** [comment]
This can be reopened. Airport was redone and runways adjusted.

**Comment by MajorTomMueller** [comment]
The whole airport is offset in its latest version in GitHub Airports!
![PHNL](https://user-images.githubusercontent.com/26853210/103898445-da4e4a80-50ec-11eb-82a2-95b44c6ab59f.png)
It neither alligne with satelite nor with FAA data.
It is moved 10ft west and 3ft north compared to FAA data, and even mor compared with satelite.

**Comment by MajorTomMueller** [comment]
apt.dat is now aligned with FAA data.
