### ISSUE TITLE
KCPR

### ISSUE THREAD

**Issue by zhf21** [InfiniteFlightAirportEditing/Navigation#2424]
# Airport ICAO
KCPR

# ICAOs issue Number in Airport repository

https://github.com/InfiniteFlightAirportEditing/Airports/issues/7176

# Runway(s) with LOC/GS
RWY 3 (ILS-Cat-I)

# References (Official sources/charts)

https://aeronav.faa.gov/d-tpp/2105/00072IL3.PDF

# What needs to be done (new add, correction freq/ID/elev./...),
Add

# Are you working on this?

Yes… but later tonight

**Comment by Daniboi737** [comment]
@zhf21 Thanks for creating and doing this for me! You are faster than me to see if it’s aprroved than myself 😂

**Comment by zhf21** [comment]
No worries, haha. I completed the ILS; I just haven’t submitted the PR. I was too tired. 

Nice work with the airport!
