### ISSUE TITLE
KSTJ

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Navigation#2440]
# Airport ICAO
KSTJ

# ICAOs issue Number in Airport repository
[7752](https://github.com/InfiniteFlightAirportEditing/Airports/issues/7752)

# Runway(s) with LOC/GS
RWY 35 ILS

# References (Official sources/charts)
[ILS or LOC RWY 35](http://aeronav.faa.gov/d-tpp/2105/00359IL35.PDF)

# What needs to be done (new add, correction freq/ID/elev./...),
coordinates fix

# Are you working on this?
No

**Comment by MajorTomMueller** [comment]
while your refference does not contain any coordinates you migth want to state where the coordinates come from and why they have changed @LawinS.
If it is because you have moved the runway during editing you should state this.

**Comment by LawinS** [comment]
Apologies, yes I did move the runway when editing the airport.

**Comment by AleksanderIF** [comment]
I'll do it
