### ISSUE TITLE
KITR

### ISSUE THREAD

**Issue by LawinS** [InfiniteFlightAirportEditing/Navigation#2456]
# Airport ICAO
KITR

# ICAOs issue Number in Airport repository
[7918](https://github.com/InfiniteFlightAirportEditing/Airports/issues/7918#issue-923921430)

# Runway(s) with LOC/GS
Runway 33 LOC

# References (Official sources/charts)
[LOC 33](https://aeronav.faa.gov/d-tpp/2106/06895L33.PDF)

# What needs to be done (new add, correction freq/ID/elev./...),
Runway was moved during editing :)

# Are you working on this?
Unfortunately, no. I'm not good with nav editing, I wish I could ):

**Comment by AleksanderIF** [comment]
Will do it, Lawin. :)
