### ISSUE TITLE
KOGD

### ISSUE THREAD

**Issue by LesterXavier** [InfiniteFlightAirportEditing/Navigation#2457]
# Airport ICAO
KOGD

# ICAOs issue Number in Airport repository
https://github.com/InfiniteFlightAirportEditing/Airports/issues/7122

# Runway(s) with LOC/GS
RWY 3

# References (Official sources/charts)
https://aeronav.faa.gov/d-tpp/2106/00297IL3.PDF

# What needs to be done (new add, correction freq/ID/elev./...),
Add ILS

# Are you working on this?

No :)

**Comment by AleksanderIF** [comment]
I'll do it too.
