### ISSUE TITLE
EBBE

### ISSUE THREAD

**Issue by OscarConklin** [InfiniteFlightAirportEditing/Navigation#2486]
# Airport ICAO
EBBE

# ICAOs issue Number in Airport repository
#241

# Runway(s) with LOC/GS
22R

# References (Official sources/charts)
https://ops.skeyes.be/html/belgocontrol_static/eaip/eAIP_Main/html/index-en-GB.html
Aerodromes AD>MILITARY AERODROMES>EBBE BEAUVECHAIN (Charts are at the bottom of the page).

# What needs to be done (new add, correction freq/ID/elev./...),
Add ILS

# Are you working on this?
No

**Comment by AleksanderIF** [comment]
I'll do it😎
