### ISSUE TITLE
WAWW

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Navigation#2497]
# Airport ICAO
WAWW

# ICAOs issue Number in Airport repository
https://github.com/InfiniteFlightAirportEditing/Airports/issues/2039

# Runway(s) with LOC/GS
Runway 26 with ILS

# References (Official sources/charts)
Jeppesen Chart

# What needs to be done (new add, correction freq/ID/elev./...),
Just ILS

# Are you working on this?
No

![WhatsApp Image 2021-07-06 at 08 04 06](https://user-images.githubusercontent.com/65013493/124533955-7c04e900-de3d-11eb-914e-4b36b43a1e95.jpeg)

**Comment by LawinS** [comment]
I’ll do this one.
