### ISSUE TITLE
WAHS

### ISSUE THREAD

**Issue by adibyaputra** [InfiniteFlightAirportEditing/Navigation#2498]
# Airport ICAO
WAHS

# ICAOs issue Number in Airport repository
https://github.com/InfiniteFlightAirportEditing/Airports/issues/1350

# Runway(s) with LOC/GS
Runway 13 With ILS

# References (Official sources/charts)
Jeppesen Chart

# What needs to be done (new add, correction freq/ID/elev./...),
Just ILS

# Are you working on this?
No

![WhatsApp Image 2021-07-06 at 09 47 12](https://user-images.githubusercontent.com/65013493/124534923-714b5380-de3f-11eb-9073-ded77bcd39e4.jpeg)

**Comment by LawinS** [comment]
I’ll do this one as well.
