### ISSUE TITLE
RPVM

### ISSUE THREAD

**Issue by Arkinanta** [InfiniteFlightAirportEditing/Navigation#2519]
# Airport ICAO
RPVM

# ICAOs issue Number in Airport repository
https://github.com/InfiniteFlightAirportEditing/Airports/issues/1642

# Runway(s) with LOC/GS
Runway 04 &22 With ILS

# References (Official sources/charts)
Jeppesen Charts

# What needs to be done (new add, correction freq/ID/elev./...),
no

# Are you working on this?

No
![IMG_20210802_191911_097](https://user-images.githubusercontent.com/87354072/127854605-828984ee-bd5e-4f3f-a9b8-3c3623ab7f70.jpg)
![IMG_20210802_191908_431](https://user-images.githubusercontent.com/87354072/127854620-192aeb74-3e04-42f0-beb0-6c77782cd224.jpg)

**Comment by AleksanderIF** [comment]
Duplicate #1667 I'll continue there, I'll do it. But if you want to create an issue again, use the newer charts, 2004 is a very long time ago, they may be invalid now, use official country AIP or Eurocontrol.
![c3d91239ae16576377c511c2ea8a6fd7](https://user-images.githubusercontent.com/53284798/127858922-d889604b-5af4-40de-9b95-06ddaed4264b.png)
