### ISSUE TITLE
VOCI

### ISSUE THREAD

**Issue by Arkinanta** [InfiniteFlightAirportEditing/Navigation#2634]
### Airport ICAO

VOCI

### Airports Issue Number

1297

### Runways with ILS/LOC

Runway 09 with ILS

### References

Charts Jeppesen
![IMG_20210912_062704](https://user-images.githubusercontent.com/87354072/132963208-64718e49-ddfe-4323-8c6d-d8171303219e.jpg)

### Corrections Required

No

### Are you working on this?

No

### Additional Information

No

**Comment by Czechoslovaki** [comment]
#1162
