### ISSUE TITLE
OKBK

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Navigation#273]
Both runways were moved

**Comment by zhf21** [comment]
This airport was submitted and approved. I can fix the ILSes.

<img width="402" alt="Screen Shot 2021-05-03 at 7 40 28 AM" src="https://user-images.githubusercontent.com/67797012/116872323-ae972900-abe3-11eb-9f26-c925fdc4615d.png">
<img width="417" alt="Screen Shot 2021-05-03 at 7 41 00 AM" src="https://user-images.githubusercontent.com/67797012/116872324-af2fbf80-abe3-11eb-9e66-a7a1077a7941.png">
<img width="410" alt="Screen Shot 2021-05-03 at 7 41 13 AM" src="https://user-images.githubusercontent.com/67797012/116872325-af2fbf80-abe3-11eb-8e1f-ec90e8c58524.png">
<img width="406" alt="Screen Shot 2021-05-03 at 7 41 23 AM" src="https://user-images.githubusercontent.com/67797012/116872327-af2fbf80-abe3-11eb-89a4-b994788aca79.png">
