### ISSUE TITLE
KPWK

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#28]
Moved the airport ages ago, [KPWK](https://github.com/InfiniteFlightAirportEditing/Airports/blob/db6ac1fe8c1d9b64c19a39c6deaa41d5f08ddb60/United%20States/K---/KP--/KPWK/apt.dat)

**Comment by DavidCutler** [comment]
Fixed :)

**Comment by zhf21** [comment]
This airport was edited over three year after these ILSes were last fixed. If possible, could this issue be re-opened? The latitude and longitude need to be adjusted accordingly, along with the elevation and runway heading.

**Comment by zhf21** [comment]
The frequency has changed as well.

https://aeronav.faa.gov/d-tpp/2104/05028IL16.PDF
