### ISSUE TITLE
GBYD

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#285]
Moved the ILS runway during editing

**Comment by MajorTomMueller** [comment]
![2021-05-23 16_15_58-GBYD-1 pdf](https://user-images.githubusercontent.com/26853210/119268418-623b7980-bbe2-11eb-89ee-710507aca8ec.png)
ILS is missing in game
change assignment to @GBKarp if you don't want to do yourself
