### ISSUE TITLE
ZSQD

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Navigation#297]
Slightly moved rwy orientation while editing.

**Comment by moritzbabl** [comment]
fixed

**Comment by Czechoslovaki** [comment]
ILS needed for all runways at the new airport.

16: 
![image](https://user-images.githubusercontent.com/51279558/129253744-7c84aeeb-69c7-4d9c-9734-0dcbfb69d438.png)

17: 
![image](https://user-images.githubusercontent.com/51279558/129253811-20ab06c7-5352-448a-bb0f-edf927518ab5.png)

34: 
![image](https://user-images.githubusercontent.com/51279558/129254081-c4d3b393-8314-4538-8813-cf27a75e3141.png)

35:
![image](https://user-images.githubusercontent.com/51279558/129254163-806223c7-1572-4b75-bcdb-63aacfe19d70.png)
