### ISSUE TITLE
KCRW

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Navigation#298]
(ILS) Runway has been moved during editing process.

**Comment by IceBlue02** [comment]
Done (GS 05 deleted) https://github.com/InfiniteFlightAirportEditing/Navigation/commit/851470b2c1965ce8e9710923d24a219c4bd2b3f1

**Comment by IceBlue02** [comment]
Commit failed for some reason. Reverted, will look again tomorrow.

@carmichaelalonso is it always required to always have a matching GS for every LOC? That could be the issue.

**Comment by moritzbabl** [comment]
@IceBlue02 will you do this?

**Comment by IceBlue02** [comment]
Finally sorted this. https://github.com/InfiniteFlightAirportEditing/Navigation/commit/af99f44653e5fa24ff1fa37099a4f4db376b3794
