### ISSUE TITLE
AYXM

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#31]
♻️ 
# Summary of Navigation issue: (ILS, Waypoints, etc.)

AYXM ILS ERROR

# Runway(s) with ILS: (If any)

16

**Comment by DavidCutler** [comment]
Region please?

**Comment by HenrikBerg02** [comment]
David, the "E" in the front indicates that the airport is located in the London region.

**Comment by DavidCutler** [comment]
Amsterdam also has E...

**Comment by HenrikBerg02** [comment]
My bad. Anyway, this is airport it located in the London region.

**Comment by DavidCutler** [comment]
Thanks Henry. ;)

**Comment by carmichaelalonso** [comment]
E is actually upper Europe people. Get it right, geez.

**Comment by ItsW1ll** [comment]
**Issue now recycled to PAPG ILS**

**Comment by MajorTomMueller** [comment]
Airport is not in IF yet. Completely not in database ...

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Airports/issues/6368
Done.
ILS added as well. #1951
