### ISSUE TITLE
LUKK

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#316]

**Comment by moritzbabl** [comment]
fixed

**Comment by danisrils39** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/8258998/61089434-b3805c80-a400-11e9-969a-7ef213df2812.png)
![Screenshot (20)](https://user-images.githubusercontent.com/8258998/61089435-b3805c80-a400-11e9-9115-7e0239b03e33.png)

Hello party People, the airport was reworked and ILS adjustments might be needed.
