### ISSUE TITLE
CYWK

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Navigation#318]
Moved runway when editing (ILS Rwy 36).

**Comment by Adrien-Z** [comment]
No ILS charts available and no ILS in the files.

**Comment by zhf21** [comment]
RWY 36 ILS addition.

<img width="406" alt="Screen Shot 2021-09-30 at 10 20 06 AM" src="https://user-images.githubusercontent.com/67797012/135473033-5f018feb-fbfc-4aef-bcd2-cc1f023f4d06.png">
