### ISSUE TITLE
KTEX Glideslope

### ISSUE THREAD

**Issue by bavAVIA** [InfiniteFlightAirportEditing/Navigation#341]
KTEX has slightly different glide slope angles than the standard.
Runway 09 has a 3.55° glide path angle.
Runway 27 has a 4.00° glide path angle.

Please fix, airport is already in airport repository.
Thanks!

**Comment by Adrien-Z** [comment]
KTEX hasn't any ILS equipped runway. We aren't responsible for GPS approaches, sorry.
