### ISSUE TITLE
LFLL

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#343]

**Comment by dushyants19** [comment]
what @moritzbabl

**Comment by moritzbabl** [comment]
ILS @dushyants19, no time to edit it yet

**Comment by indianbhaji** [comment]
According to the latest Jeppesen charts, the runway identifiers have changed to 17L/R and 35L/R from 18L/R and 36L/R

**Comment by moritzbabl** [comment]
the runway numbers are changed in the apt.dat now

**Comment by indianbhaji** [comment]
Thanks, I'll take this
