### ISSUE TITLE
KAVP

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#356]
Runway 04/22 was moved while editing.
Runway 04 is ILS equipped.

**Comment by Adrien-Z** [comment]
Fixed in 2b5fd0c. RWY22 is ILS equipped too, by the way. Anyways, thanks for the report! :)

**Comment by ECoops-123** [comment]
Elevation rounded up (and tiny co-ordinate changes automatically) in improvement to airport. I'll fix this.
