### ISSUE TITLE
ZUBD

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Navigation#359]
Moved runway when editing (ILS Rwy 14) 

![zubd ils rwy 14](https://cloud.githubusercontent.com/assets/21224259/24225843/b75f7ab4-0f30-11e7-9696-c627a9130a11.jpg)

**Comment by Adrien-Z** [comment]
Fixed in 7626b84. Thanks for the including the ILS chart, made it easier for me! :)
