### ISSUE TITLE
KEGE

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#36]
For Henrik

**Comment by Aceorbit** [comment]
Hello, I recently rework the airport and messed with the runway somewhat, if anyone would like to double-check. Along with that, it's an LDA so the localizer is offset more than 3* from the runway centerline, so make what you will of that.

[06403LDA25.PDF](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5839803/06403LDA25.PDF)
