### ISSUE TITLE
VVTS

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#386]
Runways 07L/25R and 07R/25L have been moved.

**Comment by indianbhaji** [comment]
I'll take this

**Comment by aads552** [comment]
Runway moved during redo, need ILS fix for 25R,25L,07R

**Comment by IFUA2003** [comment]
I extended runway 25R/07L a little bit. Please fix the ILS 25R of the runway

**Comment by zhf21** [comment]
I can take care of this.
