### ISSUE TITLE
CYBG

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#39]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYBG ILS ERROR

# Runway(s) with ILS: (If any)

11

**Comment by HenrikBerg02** [comment]
I believe all the fixes in the image has been added. Not sure about the VORs though.

**Comment by zhf21** [comment]
RWY 11 ILS needs to be added + corrections.

<img width="400" alt="Screen Shot 2021-09-28 at 10 43 14 PM" src="https://user-images.githubusercontent.com/67797012/135194226-57e0fadb-b2dd-453e-a3f0-69dc5b45b4a7.png">

<img width="400" alt="Screen Shot 2021-09-28 at 10 43 33 PM" src="https://user-images.githubusercontent.com/67797012/135194262-f863fd15-6383-4a83-9b21-bc2e2e762981.png">
