### ISSUE TITLE
EGLL STAR's and SID's

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#392]
Adding fixes for London Heathrow 

http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=94&Itemid=143.html

**Comment by Will171** [comment]
#396

**Comment by ItsW1ll** [comment]
New Fixes for EGLL 
LLS01
AMTOD

**Comment by ItsW1ll** [comment]
Added in #889
