### ISSUE TITLE
CYHM

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#403]
Runway 12/30 moved.

**Comment by Adrien-Z** [comment]
Fixed in e568f85. Thanks for the report! :)

**Comment by zhf21** [comment]
ILS-cat-I -> ILS-cat-II.

<img width="407" alt="Screen Shot 2021-09-28 at 11 40 45 PM" src="https://user-images.githubusercontent.com/67797012/135199352-2d884185-5d94-40b4-a394-42815478b258.png">
