### ISSUE TITLE
CYEB

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#42]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYEB ILS ERROR

# Runway(s) with ILS: (If any)

34

**Comment by MajorTomMueller** [comment]
Airport is not in IF, ICAO Code not found ....

**Comment by velocity23** [comment]
Airport now has ICAO Code PF2 (technically I think CPF2 but it's PF2 in IF). Doesn't seem to have an ILS so I might close this, if anyone else finds something that proves otherwise we can reopen.
