### ISSUE TITLE
KLAS

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#421]
Runways moved, length and width modified. Runways 01L, 25R and 25L with ILS.

**Comment by ewanfleming** [comment]
Runway numbers changes. The 25L/07R is now 26L/08R and 25R/07L is now 26R/08L

**Comment by Aviationluver** [comment]
RWY's 26L/R show up as GPS approaches in the sim. Is is possible to change these to ILS approaches?

**Comment by ItsW1ll** [comment]
Doing it now @Aviationluver
