### ISSUE TITLE
KSAN

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#427]
Runway data changed (length and width). Runway 09 has ILS.

**Comment by Adrien-Z** [comment]
Fixed in 55c8464.

**Comment by CptNathanHope** [comment]
Added LOC for 27 in [`639e5ea`](https://github.com/InfiniteFlightAirportEditing/Navigation/commit/639e5ea8871fe61b0f161790c5939178614d5386) as per: https://flightaware.com/resources/airport/SAN/IAP/LOC+RWY+27/pdf
