### ISSUE TITLE
CYFI

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#43]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYFI ERROR

# Runway(s) with ILS: (If any)

35

**Comment by Swang007** [comment]
Still open! I couldn't find enough information on this VOR

**Comment by HenrikBerg02** [comment]
I updated some of the NDB information but couldn't find enough information on the VOR, as you said.

**Comment by HenrikBerg02** [comment]
Insufficient information provided.

**Comment by brennanhackard** [comment]
Fixed in #1504
