### ISSUE TITLE
KGYY

### ISSUE THREAD

**Issue by DeerCrusher** [InfiniteFlightAirportEditing/Navigation#432]
I was flying into KGYY this afternoon in the Chicago region and noticed that the GPS cone was pretty far off. I used some lines to show where the cone is, as it was a little difficult to see from the raw image. The red lines in the mini map are the outer edges of the cone and the black line is the center line. you can see that I was essentially on centerline with the CDI needle on the bottom. I suppose the real issue is how the cone is depicted on the map rather than the accuracy of the navigation equipment. Again, not sure if the “cone” editing is within your fortei, but thought I’d bring it to your attention. Let me know if this should be posted on the forum and I can do so. Thanks and let me know if there is anything else that I can further clarify. The GPS 02 is in question. Aircraft utilized was the Cessna 208.

![img_0426](https://cloud.githubusercontent.com/assets/25359079/25972957/5dddc436-365f-11e7-81cb-87e62d67634c.PNG)

![img_0427](https://cloud.githubusercontent.com/assets/25359079/25972962/607793ca-365f-11e7-9d53-b3457a665e69.PNG)

**Comment by Adrien-Z** [comment]
Hi there. Unfortunately, we are unable to fix that on our end as GPS approaches are handled automatically in Infinite Flight. I am therefore closing this issue. Creating a [support topic on the community](https://community.infinite-flight.com/t/kgyy-gps-02-cone-issue/116017?u=adrien) like you did is the only way FDS could possibly take care of this issue. Hope you understand. :)
