### ISSUE TITLE
KLUK

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Navigation#435]
ILS on runway 21L needs to be adjusted.

**Comment by CptNathanHope** [comment]
Fixed. :)

**Comment by dushyants19** [comment]
https://community.infinite-flight.com/t/kluk-ils-issue/189322?u=dush19

**Comment by kilt46** [comment]
This airport has been realigned. ILS needs fixed

**Comment by ItsW1ll** [comment]
ILS fixed
