### ISSUE TITLE
KESC

### ISSUE THREAD

**Issue by ryu12332** [InfiniteFlightAirportEditing/Navigation#454]
9/27 tweaked.

**Comment by bavAVIA** [comment]
Please only create ILS issues when the airport has been approved and taken into the repository. Thanks.

**Comment by ItsW1ll** [comment]
@bavAVIA has the airport been committed?

**Comment by brunocr98** [comment]
The issue is closed, so I think yes. 

https://github.com/InfiniteFlightAirportEditing/Airports/issues/1911

**Comment by Adrien-Z** [comment]
Fixed by @ItsW1ll in 0b4e4c2.
