### ISSUE TITLE
KCAK

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#458]
Runways' data modified (runway 05/23 was shifted). All runways have ILS.

Source: http://www.fltplan.com/AirportInformation/CAK.htm

**Comment by ItsW1ll** [comment]
Has this been committed?

**Comment by Adrien-Z** [comment]
Nope, you can fix it if you want. :)

**Comment by ItsW1ll** [comment]
Fixing it now :)

**Comment by Adrien-Z** [comment]
Fixed by @ItsW1ll in d4f644e.
