### ISSUE TITLE
CYKA

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#46]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYKA ILS ERROR

# Runway(s) with ILS: (If any)

09

**Comment by Swang007** [comment]
![image](https://cloud.githubusercontent.com/assets/11000109/13957418/654f257a-f01a-11e5-8638-2bbcac385eec.png)

**Comment by HenrikBerg02** [comment]
I'm stuck... Can't find the slaved variation, frequency, and reception range from the diagram...

**Comment by Swang007** [comment]
Still doing this one or should I?

**Comment by HenrikBerg02** [comment]
You do it.

**Comment by brennanhackard** [comment]
Fixed in #1504

**Comment by zhf21** [comment]
RWY 29 LOC addition.

<img width="404" alt="Screen Shot 2021-09-29 at 8 17 05 AM" src="https://user-images.githubusercontent.com/67797012/135266703-efbe25ad-8c3f-42e1-ae5b-50fabd071af6.png">

*Will complete later.*
