### ISSUE TITLE
LKKU

### ISSUE THREAD

**Issue by Hornet199** [InfiniteFlightAirportEditing/Navigation#466]
Runway length and width modified, moved. 21 have ILS.
Chart: [http://lis.rlp.cz/ais_data/aip/data/valid/a2-ku-ndb20c.pdf](url)
Note: chart is not actual, runway change: 20 to 21

**Comment by indianbhaji** [comment]
I'll take this

**Comment by indianbhaji** [comment]
No ILS here, please close!
