### ISSUE TITLE
KSNA

### ISSUE THREAD

**Issue by Adrien-Z** [InfiniteFlightAirportEditing/Navigation#468]
_**SIDs:**_

## ANAHEIM NINE:
 http://155.178.201.160/d-tpp/1706/00377ANAHEIM.PDF
    **Missing:**
		DARTS 34-09-21.7700N 118-16-10.5400W
	**Outside Region:**
		VTU 34-06-54.213N 119-02-58.170W

## CHANNEL THREE:
http://155.178.201.160/d-tpp/1706/00377CHANNEL.PDF
	**Missing:**
		LANDO 35-00-44.7400N 118-36-58.9400W
	**Outside Region:**
		EHF 35-29-04.397N 119-05-50.257W
		RZS 34-30-34.321N 119-46-15.570W

## EL TORO FOUR: 
http://155.178.201.160/d-tpp/1706/00377ELTORO.PDF
	**Missing:**
		ELB 33-40-33.707N 117-43-51.901W
		ZENAP 33-34-52.1200N 117-24-12.0600W
		BONDO 33-11-39.6300N 117-01-38.2500W
	**Outside Region:**
		IPL 32-44-55.920N 115-30-30.895W
		GWIRE 32-45-31.2600N 115-54-22.8400W

## FINZZ ONE: 
http://155.178.201.160/d-tpp/1706/00377FINZZ.PDF
	**Missing:**
		DOLLF 33-28-50.0900N 118-00-07.2400W
		FINZZ 33-34-58.8000N 118-07-59.9000W
		CAHIL 33-54-22.5700N 117-56-41.2500W
		ZOOMM 33-57-09.4100N 117-54-08.9100W
		PLAYY 34-17-59.3400N 117-27-52.8100W
		ARCUS 34-32-30.0000N 117-06-06.4200W
		YELAH 34-51-15.0000N 116-38-40.9000W
		NNAVY 34-55-10.6800N 116-43-40.8800W
		GUNNR 34-52-37.0000N 116-59-13.0000W
	**Outside Region:**  
		WYZEE 35-41-45.9200N 115-30-12.6900W
		BEALE 36-10-56.8300N 114-49-34.0900W
		BLAZN 35-37-55.2100N 115-46-46.0600W
		LAS 36-04-46.931N 115-09-35.272W
		ARRMY 35-03-48.0000N 116-44-24.0000W
		HAILO 35-38-14.0000N 115-58-16.0000W

## HAWWC ONE: 
http://155.178.201.160/d-tpp/1706/00377HAWWC.PDF
	**Missing:**
		PIJIN 33-52-03.1900N 118-19-42.8000W
		HAWWC 33-54-54.9200N 118-24-50.7600W
		WROBN 34-00-26.8900N 118-29-40.1000W
		ORIYL 34-03-12.7800N 118-35-34.0700W
		MOOOS 34-03-04.6900N 118-45-38.9200W
	**Outside Region:**
		IKAYE 34-08-35.0000N 119-00-37.0000W

## HHERO ONE: 
http://155.178.201.160/d-tpp/1706/00377HHERO.PDF
	**Missing:**
		MIKAA 33-24-34.7100N 118-08-47.3400W
		SNYPR 33-26-22.0000N 118-18-00.1000W
		HHERO 33-31-16.9600N 118-29-16.3800W
		BRDYY 33-41-40.8800N 118-37-58.3500W
		CMINO 33-43-53.7100N 118-27-34.0100W
		RIDDL 34-00-07.3000N 118-27-35.2800W

## HOBOW ONE: 
http://155.178.201.160/d-tpp/1706/00377HOBOW.PDF
	**Missing:**
		LIION 33-43-59.6300N 117-49-58.4100W
		CHOAK 33-45-20.0100N 117-45-29.1800W
		JAABB 33-42-07.6900N 117-42-45.9800W
		KLNCH 33-39-00.2500N 117-43-57.9300W
		TKDWN 33-37-38.0600N 117-48-12.8800W
		TRAYN 33-39-35.2300N 117-53-57.9400W
		JUMPP 33-42-52.9300N 117-58-00.7300W
		HOBOW 33-47-49.8800N 118-00-23.4800W

## PIGGN ONE: 
http://155.178.201.160/d-tpp/1706/00377PIGGN.PDF
	**Missing:**
		WIILD 33-30-17.3400N 117-13-59.8800W
		OTAYY 32-39-54.4500N 117-06-58.4500W
		TCATE 32-48-29.0700N 116-28-59.8800W
		FLWRZ 33-29-53.0000N 116-54-05.9000W
		BLCKD 33-29-31.7700N 116-25-28.1400W
		FNCHH 33-34-38.2000N 117-14-22.8000W
		TBERD 33-37-44.2100N 116-59-51.9100W
		PEELR 33-36-39.6200N 116-20-12.9600W
	**Outside Region:**
		CSTWY 33-29-09.7700N 116-02-03.0500W
		CNERY 33-37-03.7500N 115-34-56.7200W
		MTBAL 33-36-11.9300N 116-02-32.3000W
		AVRRY 33-45-07.3500N 115-34-14.5600W
		WURMO 34-15-13.0000N 114-41-26.0000W
		LVELL 34-12-37.3800N 115-36-53.2500W
		TTRUE 34-38-01.5300N 114-23-05.0500W

## PLZZA ONE: 
http://155.178.201.160/d-tpp/1706/00377PLZZA.PDF
	**Missing**
		SHMRQ 33-48-32.2500N 117-54-08.8200W
		PLZZA 33-52-19.9200N 117-52-34.1800W
		KULVR 34-12-52.7700N 118-12-30.9900W
		CUTOR 33-52-27.1400N 117-46-32.6500W
		DRGON 33-52-54.3000N 117-40-16.9900W

## STREL FOUR: 
http://155.178.201.160/d-tpp/1706/00377STREL.PDF
	**Missing:**
		PILLO 32-46-13.3900N 116-28-06.8600W

# Progress
- [x] ANAHEIM NINE
- [ ] CHANNEL THREE
- [ ] EL TORO FOUR
- [ ] FINZZ ONE
- [ ] HAWWC ONE
- [ ] HHERO ONE
- [ ] HOBOW ONE
- [x] PIGGN ONE
- [x] PLZZA ONE
- [x] STREL FOUR

**Comment by dushyants19** [comment]
Pizza? Are you sure you didnt misspell that one? :pizza:

**Comment by ItsW1ll** [comment]
Fixed in previous update
