### ISSUE TITLE
CYMS

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#47]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYMS ILS ERROR

# Runway(s) with ILS: (If any)

29R

**Comment by Swang007** [comment]
http://community.infinite-flight.com/t/missing-vors-at-egll/31196

**Comment by HenrikBerg02** [comment]
@Swang007, Woodley is a NDB. Could you add an NDB label?

**Comment by MajorTomMueller** [comment]
CYMS airport is not in IF, not in database at all, not found in Navigraph, ICAO Code not found
