### ISSUE TITLE
CYMM

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#48]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

CYMM ILS ERROR

# Runway(s) with ILS: (If any)

25 Needs to be changed to 26. 

# References: (Official sources/charts)

InfiniteFlightAirportEditing/Airports#2500 - runway needs further update

**Comment by HenrikBerg02** [comment]
I already completed this a long while back.

**Comment by brennanhackard** [comment]
Fixed in #1504

**Comment by zhf21** [comment]
Runway renamed to 08/26. Will update ILS.

<img width="407" alt="Screen Shot 2021-09-29 at 10 06 12 AM" src="https://user-images.githubusercontent.com/67797012/135284804-9825eea3-8950-4ecb-83a5-081f3cdb7936.png">

*Will do later.*
