### ISSUE TITLE
LFKF

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#487]
Runway was moved while editing, 23 is ILS equipped.

**Comment by Adrien-Z** [comment]
Fixed in 434e335. Thanks for the report! :)

**Comment by zhf21** [comment]
Runway was moved during editing. I will fix this.

<img width="302" alt="Screen Shot 2021-06-23 at 3 44 39 PM" src="https://user-images.githubusercontent.com/67797012/123158581-fb57ed00-d439-11eb-9826-a34bdcefc02a.png">

https://storage.ivao.fr/lfmm_public/Fiche_AD/Fiche_LFKF.pdf
