### ISSUE TITLE
KPWM 

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#496]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

**ILS equipped:**
Runway 11
Runway 29

**Comment by CptNathanHope** [comment]
Fixed.

**Comment by CptNathanHope** [comment]
Runways slightly shifted during editing. Will fix as soon as possible.

**Comment by Velocity23** [comment]
Working on this
