### ISSUE TITLE
KLAX

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#5]
Approach system will have to be recalibrated once KLAX's apt.dat has been submitted to the /Airports repository.

**Comment by DavidCutler** [comment]
Do these still need editing?

**Comment by Swang007** [comment]
I don't think so. I just tried out some auto land approaches here and they were all pretty close (if not, within) the TDZ

**Comment by moritzbabl** [comment]
Runway moved again during redo
