### ISSUE TITLE
MMMX

### ISSUE THREAD

**Issue by lalomarlin** [InfiniteFlightAirportEditing/Navigation#500]
Fixing ILS Runways 05R/23L

**Comment by lalomarlin** [comment]
Fixed https://github.com/InfiniteFlightAirportEditing/Navigation/commit/df5a704d2214f254407feb47cb8d70830c95c58a#diff-e06f3bd2590695ce173c64abb4fae882

**Comment by Adrien-Z** [comment]
Fixed by @lalomarlin in 6d0b41f.

**Comment by MajorTomMueller** [comment]
Anything to do @velocity23 ?

**Comment by velocity23** [comment]
I believe the runways were moved in the most recent airport update

**Comment by MajorTomMueller** [comment]
https://github.com/InfiniteFlightAirportEditing/Navigation/commit/94b8c5491355a4df2223ba59eba003270bcf3a14

**Comment by zhf21** [comment]
I flew the ILS for RWY 23L in Infinite Flight this evening and noticed incorrect localizer and glideslope capture. I will be fixing this along with a few other corrections (elevation and coordinates).

![unknown](https://user-images.githubusercontent.com/67797012/116960007-3a08cc80-ac6d-11eb-9310-41833e69b7ab.png)

![unknown-1](https://user-images.githubusercontent.com/67797012/116960009-3bd29000-ac6d-11eb-9bb0-1cca13d02b05.png)
