### ISSUE TITLE
Chennai Fixes

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#501]
There is a lot, I will add them all eventually but i'll require any help available 

http://www.aai.aero/public_notices/29-2009.pdf
Page 7

**Comment by Ralphy444** [comment]
I will help out with this issue.

**Comment by indianbhaji** [comment]
I can help

**Comment by dushyants19** [comment]
I hardly did anything. Thanks guys :)
