### ISSUE TITLE
YSCB

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#51]
http://community.infinite-flight.com/t/yscb-rnav-p-rwy-35-missing-vatga-and-cb547/31506

**Comment by HenrikBerg02** [comment]
Insufficient information provided.

**Comment by Swang007** [comment]
Runway 35's ILS seems off, will adjust LOC

**Comment by henrikbg** [comment]
@Swang007, did you complete this? If not, I'll fix it.

**Comment by Swang007** [comment]
I did not; I couldn't remember how to readjust these / where to get proper coordinates.

**Comment by henrikbg** [comment]
Ok, I'll do it.

**Comment by ItsW1ll** [comment]
ILS Error
Name: GS, Identifier: ICB with true heading 180.0° is 180° off of airport YSCB's runway 35 true heading of 0.0°.
