### ISSUE TITLE
WSSS waypoints on the ILS

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#52]
http://community.infinite-flight.com/t/ils-dme-rwy-02c-wsss-missing-every-waypoint/31634

**Comment by HenrikBerg02** [comment]
I'm having trouble with this one. @InfiniteFlightAirportEditing/navigation-data-editors could you guys help me out here?

**Comment by DavidCutler** [comment]
What are you having trouble with? Finding the VORS?

**Comment by HenrikBerg02** [comment]
No. I'm having trouble with coordinates on the fixes.

**Comment by HenrikBerg02** [comment]
Insufficient information provided.
