### ISSUE TITLE
LLBG

### ISSUE THREAD

**Issue by sumith11** [InfiniteFlightAirportEditing/Navigation#524]
Runways moved while editing
ILS: RWY 08/26 & RWY 12/30 

*Reference:* http://en.caa.gov.il/index.php?option=com_content&view=article&id=414&Itemid=278

**Comment by MajorTomMueller** [comment]
What needs to be done / why is this reopened?

**Comment by MBeringuy** [comment]
@MajorTomMueller Looking at the file, it seems to me that some clues are missing from ILS. I'll do it.
