### ISSUE TITLE
LEVX

### ISSUE THREAD

**Issue by lolo31r** [InfiniteFlightAirportEditing/Navigation#531]
ILS runway 19 moved

**Comment by Adrien-Z** [comment]
Fixed in 7b7fd2c. Thanks for the report! :)

**Comment by brunocr1050** [comment]
Runway moved, numbers changed from 02/20 to 01/19

https://aip.enaire.es/AIP/contenido_AIP/AD/AD2/LEVX/LE_AD_2_LEVX_en.pdf
(Page 16)
