### ISSUE TITLE
CYCD

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Navigation#546]
Runway extended and position adjusted.

**Comment by lalomarlin** [comment]
I'll take this one

**Comment by lalomarlin** [comment]
![imagen](https://user-images.githubusercontent.com/20364014/28285916-0a1d8fe4-6afc-11e7-8054-3ca07922155b.png)
No ILS on this one.

**Comment by indianbhaji** [comment]
There is ILS on this one, I have the charts - I'll take it if you want? @lalomarlin

**Comment by lalomarlin** [comment]
Not really a problem, I can just add it ;)

**Comment by lalomarlin** [comment]
Also, the airport is still under construction

**Comment by DelsterX** [comment]
Status Update: This airport has now been submitted for review.

**Comment by Adrien-Z** [comment]
Please only create ILS issues when the airport has been approved. Thanks! :)

**Comment by DelsterX** [comment]
Airport now approved. Ready for ILS runway update.
