### ISSUE TITLE
VDPP

### ISSUE THREAD

**Issue by Yifan081** [InfiniteFlightAirportEditing/Navigation#557]
ILS Rwy 23

**Comment by Adrien-Z** [comment]
Fixed in ba9121e. Thanks for the report! :)

**Comment by zhf21** [comment]
Removal of duplicate ILS.

<img width="1440" alt="Screen Shot 2021-09-28 at 3 48 52 PM" src="https://user-images.githubusercontent.com/67797012/135155821-e472b6b1-0dd0-443b-a1e4-1110752bc66d.png">

<img width="410" alt="Screen Shot 2021-09-28 at 3 49 04 PM" src="https://user-images.githubusercontent.com/67797012/135155854-d8b988a6-b89a-4353-870f-4655ae7c6e95.png">
