### ISSUE TITLE
Missing Scottish fixes 

### ISSUE THREAD

**Issue by ThomasRalph1** [InfiniteFlightAirportEditing/Navigation#561]
R2248
TRN07
TRN29
TRN70

As per:
 www.opennav.com/waypoint/UK/R2248
www.opennav.com/waypoint/UK/TRN07
www.opennav.com/waypoint/UK/TRN29
www.opennav.com/waypoint/UK/TRN70

I will add these in.

**Comment by Ralphy444** [comment]
Added in 6c8857944e22677b01b6dd128143aa9854a23ee6

**Comment by ItsW1ll** [comment]
That commit only shows that you have removed KKP?

**Comment by ItsW1ll** [comment]
this one has failed?

**Comment by ThomasR01** [comment]
Added in 194e2f804ddbb59a2368a337b30f861c7423aac0

**Comment by ItsW1ll** [comment]
R2248 where is that??

**Comment by ThomasR01** [comment]
Double checked. I've just noticed that it's not in use anymore. Will get it removed.
