### ISSUE TITLE
KVNY SID

### ISSUE THREAD

**Issue by insertusernameh3r3** [InfiniteFlightAirportEditing/Navigation#584]
New SID JANNY3, missing fixes:
WABBT - 34.3678278, -118.5741833
ELMRR - 34.4807139, -118.4865889
COWWS - 34.7042389, -117.6287667
BASAL - 34.7577750, -116.8618306
JOHHN - 34.7730583, -116.7053889
DNUTT - 34.7873944, -116.5566722 
GLAZD - 34.9773278, -116.3282972
WNCHL - 35.0070722, -116.1837611
KREME - 34.9190333, -116.2179611
JOEES - 34.7980194, -116.2399694
TAAAP - 34.7904028, -115.8197944

**Comment by indianbhaji** [comment]
Are you doing this? If not, I'll take it since it's a quick 5 min job

**Comment by Spinxzl** [comment]
I'm doing it :)

**Comment by indianbhaji** [comment]
Cool!

**Comment by zhf21** [comment]
ILS for RWY 16R needs an update. RWY 16L needs an ILS added. I'll take care of it.

**Comment by zhf21** [comment]
https://aeronav.faa.gov/d-tpp/2103/00552IZ16R.PDF
