### ISSUE TITLE
Missing waypoints

### ISSUE THREAD

**Issue by liamkirky** [InfiniteFlightAirportEditing/Navigation#590]
I'll be adding missing waypoints that i can find around the globe.

WATSS

**Comment by moritzbabl** [comment]
Could you maybe elaborate a bit more? ^^ I think there are more waypoints in the U.K. that are missing

**Comment by liamkirky** [comment]
I will be finding waypoints in the U.K and adding them. I will be editing the comment with waypoints im going to be adding

**Comment by liamkirky** [comment]
Will has a system for the UK waypoints so I'm going to leave it to him, I'll find some more waypoints elsewhere. I will keep this issue open but it will include other missing waypoints
