### ISSUE TITLE
LGRP

### ISSUE THREAD

**Issue by moritzbabl** [InfiniteFlightAirportEditing/Navigation#591]
Runway moved during editing

**Comment by MajorTomMueller** [comment]
please reopen, Runway numbering was changed:
https://github.com/InfiniteFlightAirportEditing/Airports/commit/3da604b220860a46585047164639f54fceba3b16
[LG_AD_2_LGRP_en_2020-12-31.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/5776238/LG_AD_2_LGRP_en_2020-12-31.pdf)
Runway 24 has ILS

**Comment by RyanEpps** [comment]
Blame Tom if this isn’t supposed to be reopened.
