### ISSUE TITLE
KORD

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#6]
ILS for runways 10L/28R and 10C/28C is missing.

**Comment by ItsW1ll** [comment]
Errors occurred on Val's checks

**Comment by brunocr98** [comment]
Airport uploaded, you may now go ahead.

-----
Runways with ILS:
- 10L/28R
- 10C/28C
- 10R/28L
- 4R/22L
- 22R
- 9R/27L
- 9L/27R

Runways removed: 15/33 (charts provided indicate that this one is closed).
