### ISSUE TITLE
UK Fixes

### ISSUE THREAD

**Issue by indianbhaji** [InfiniteFlightAirportEditing/Navigation#605]
Title says it all - eight hundred and twenty seven uk fixes

**Comment by indianbhaji** [comment]
This updates fix coordinates and adds new fixes

**Comment by liamkirky** [comment]
Why not let will do this? He has something for it and has done most of them.

**Comment by ItsW1ll** [comment]
Up to you, I'm happy to take over this if need be  :)

**Comment by indianbhaji** [comment]
Well, I have no idea how you want to take over this when I've already done them all?

**Comment by ItsW1ll** [comment]
have they been committed?

**Comment by ItsW1ll** [comment]
New Fixes as part of the new airways introduced in amendments doc 2017/07.

**Comment by ItsW1ll** [comment]
Pretty much all completed now
