### ISSUE TITLE
KHWO

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#64]
Runways were moved, rotated. [KHWO](https://github.com/InfiniteFlightAirportEditing/Airports/blob/4.0/United%20States/K---/KH--/KHWO/apt.dat)

**Comment by NickArt1342** [comment]
okay, this is the fourth airport I wanted to open an issue for today and you opened it just a day ago before me..

**Comment by dushyants19** [comment]
I moved the airport yesterday, @NickArt1342.

**Comment by HenrikBerg02** [comment]
@dushyants19, this airport doesn't have any ILS approaches. Don't create an issue for airports without ILS approaches. GPS approaches are handled by Infinite Flight.
