### ISSUE TITLE
EHLE

### ISSUE THREAD

**Issue by NickArt1342** [InfiniteFlightAirportEditing/Navigation#65]
ILS 05 shows bearing 226 instead of 46.

**Comment by HenrikBerg02** [comment]
The bearing shows 46 in the navigation files.

**Comment by dushyants19** [comment]
I'll check it in WED. Might be something like HWO, YGDO

**Comment by ItsW1ll** [comment]
Bearing is off
Name: GS, Identifier: LSD with true heading 227.7° is 180° off of airport EHLE's runway 05 true heading of 47.5°.
