### ISSUE TITLE
RPVB

### ISSUE THREAD

**Issue by superven13** [InfiniteFlightAirportEditing/Navigation#664]
ILS Issue

**Comment by Adrien-Z** [comment]
Why did you close this? This airport has been approved and it has an ILS approach, so it needs to be adjusted.

**Comment by superven13** [comment]
@Adrien-Z I accidentally click on the close when I am trying some features in github

**Comment by CptNathanHope** [comment]
# Runway(s) with ILS:

03

# References:

http://sharepoint.aag.ph/portal/Downloads/Terminal%20Charts/RPVB.pdf
