### ISSUE TITLE
CYXS

### ISSUE THREAD

**Issue by DelsterX** [InfiniteFlightAirportEditing/Navigation#676]
ILS position requires attention after runway 15/33 adjustment

**Comment by DelsterX** [comment]
This is still an issue. Currently in the sim runways are showing wrong headings for the ILS. How long does this take to resolve?

**Comment by Adrien-Z** [comment]
Our navigation editing website is currently down. Once it is back & fully operational, we'll fix it. Thanks for your understanding!

**Comment by ItsW1ll** [comment]
#1129 Fixed

**Comment by zhf21** [comment]
There is no evidence that RWY 33 has an ILS. RWY 15 does, however.

<img width="414" alt="Screen Shot 2021-09-30 at 11 33 48 AM" src="https://user-images.githubusercontent.com/67797012/135486115-44a6d893-bc17-41da-8670-1ad6da01e631.png">
