### ISSUE TITLE
ZHCC

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Navigation#691]
Recycled ♻️ 

# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

30L/R 12L/R

**Comment by brunocr98** [comment]
I'll be editing this airport in a few days. The airports' 2 runways have ILS. 

http://vau.aero/navdb/chart/ZHCC.pdf

**Comment by ItsW1ll** [comment]
Cheers, let us know when it has been committed!

**Comment by brunocr98** [comment]
Airport uploaded to the repo, you may now go ahead.

**Comment by ItsW1ll** [comment]
Runway heading is WAY off!! 
Name: GS, Identifier: IFF with true heading 2112.4° is 1635° off of airport ZHCC's runway 12R true heading of 112.4°.
