### ISSUE TITLE
KLAF

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Navigation#695]
10/28 ILS

**Comment by CptNathanHope** [comment]
No ILS for 28.

**Comment by ShaneAviation** [comment]
Runway 10's ILS needs an adjustment. I'll take care of it.

![image](https://user-images.githubusercontent.com/68622529/113372994-7922c580-932f-11eb-9f2e-48d427dbf44e.png)

**Comment by zhf21** [comment]
What kind of teacher doesn't check to make sure this wasn't already done! I'm awful!

_Disregard comment. Apolgies._
