### ISSUE TITLE
LTFM STAR/SID

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#7]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

(ISSUE RECYLED) LTFM Waypoints

# Runway(s) with RNAV: (If any)

34L 35R, 16R, 17L

# References: (Official sources/charts)

See Kilt

**Comment by Rotate-FDS** [comment]
I would say that fixes should be handled individually.

**Comment by carmichaelalonso** [comment]
In this instance it's probably easier if you group by region

**Comment by ItsW1ll** [comment]
Added
