### ISSUE TITLE
CYQQ

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Navigation#713]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS: (If any)

12/30

# References: (Official sources/charts)

< Enter text here >

**Comment by zhf21** [comment]
RWY 30 ILS addition + data correction.

<img width="405" alt="Screen Shot 2021-09-29 at 10 38 05 AM" src="https://user-images.githubusercontent.com/67797012/135290905-1024cd2e-43bb-45af-8c19-701f5cd81991.png">

<img width="410" alt="Screen Shot 2021-09-29 at 10 38 19 AM" src="https://user-images.githubusercontent.com/67797012/135290943-cc1be637-5df3-4453-a204-282a3f20a44f.png">
