### ISSUE TITLE
EICK

### ISSUE THREAD

**Issue by ewanfleming** [InfiniteFlightAirportEditing/Navigation#715]
Runway Moved while editing.

**Comment by kztmtn** [comment]
Lost ILS (?) RWY 16/34. I'll handle this.

[EI_AD_2_EICK_24-19.1_en.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4279402/EI_AD_2_EICK_24-19.1_en.pdf)
[EI_AD_2_EICK_24-22_en.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/4279403/EI_AD_2_EICK_24-22_en.pdf)

**Comment by kztmtn** [comment]
Runway number changed, Completed.

**Comment by ECoops-123** [comment]
Runways moved in commit. I'll do this.
