### ISSUE TITLE
KRST

### ISSUE THREAD

**Issue by brunocr98** [InfiniteFlightAirportEditing/Navigation#727]
Runway data changed. Runway 13/31 with ILS.

**Comment by Gabe-Z** [comment]
ILS

Runway 13/31 position changed.

https://www.faa.gov/aero_docs/dtpp/1905/05041IL13.PDF#nameddest=(RST)
https://www.faa.gov/aero_docs/dtpp/1905/05041IZLZ31.PDF#nameddest=(RST)

**Comment by Velocity23** [comment]
Working on this
