### ISSUE TITLE
LIPY

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Navigation#730]
Runway totally redone. Has ILS

**Comment by johanneskkl** [comment]
may I get assigned?

**Comment by dushyants19** [comment]
Accept invite here: https://github.com/InfiniteFlightAirportEditing/Navigation/invitations

**Comment by johanneskkl** [comment]
there is a problem: the field elevation is 0. Probably the reviewer did not check. I will send the apt to airports again before continuing here

**Comment by brennanhackard** [comment]
Fixed in #1504
