### ISSUE TITLE
FAOR

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Navigation#733]
ISSUE: There should be ILS approach systems on all runways except for 21R.

**Comment by MajorTomMueller** [comment]
done. ILS for all rwy as of latest charts:
http://www.caa.co.za/Aeronautical%20Charts/O.R.%20Tambo%20INTL%20-%20FAOR/FAOR_AERODROME%20CHART_AD-01.pdf

**Comment by brennanhackard** [comment]
Fixed in #1504
