### ISSUE TITLE
ZSSS

### ISSUE THREAD

**Issue by Adrien-Z** [InfiniteFlightAirportEditing/Navigation#737]
ILS is missing on all runways, thanks @Alchonub :)

**Comment by ItsW1ll** [comment]
Lots of data missing. Will need an urgent fix

**Comment by ItsW1ll** [comment]
♻️

**Comment by CptNathanHope** [comment]
# Runways with ILS:

All (18L/36R, 18R/36L).

# References: 

http://opennav.com/pdf/ZSSS/ZSSS-10A.pdf
http://opennav.com/pdf/ZSSS/ZSSS-10B.pdf
http://opennav.com/pdf/ZSSS/ZSSS-10C.pdf
http://opennav.com/pdf/ZSSS/ZSSS-10D.pdf
