### ISSUE TITLE
EGPK STAR's & SID's 

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Navigation#74]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

New waypoints added for EGPK

# References: (Official sources/charts)
RW12 : 553054.82N 0043641.31W
RW21 : 553012.19N 0043432.76W
RW30 : 553008.68N 0043427.83W

http://www.nats-uk.ead-it.com/aip/current/amend28/EG_Amdt_A_2019_03_E_en.pdf

**Comment by HenrikBerg02** [comment]
I don't think this is the correct chart. Could you double check, @samuelandersson? I can't find JAYBEE or BIDUS.

**Comment by samuelandersson** [comment]
Updated for you @HenrikBerg02. Thanks for helping!

**Comment by Velocity23** [comment]
Will work on this
