### ISSUE TITLE
RCTP

### ISSUE THREAD

**Issue by dushyants19** [InfiniteFlightAirportEditing/Navigation#740]
Needs ILS on all runways

http://eaip.caa.gov.tw/eaip/history/2016-01-21/html/eAIP/RC-AD-2.RCTP-en-TW.html

**Comment by aads552** [comment]
Runways moved after rework
ILS 05R/23L, 05L/23R

http://eaip.caa.gov.tw/eaip/history/2019-03-14/html/index-en-TW.html?target=http%3A//eaip.caa.gov.tw/eaip/history/2019-03-14/html/eAIP/RC-AD-2.RCTP-en-TW.html%23AD-2&menuState=http%3A//eaip.caa.gov.tw/eaip/history/2019-03-14/html/eAIP/RC-menu-en-TW.html,GEN,ENR,AD,AD-2
