### ISSUE TITLE
EGKB

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#755]
ILS - RWY 12 ONLY

**Comment by ewanfleming** [comment]
Fixed, awaiting review.
#762

**Comment by ewanfleming** [comment]
Fixed in https://github.com/InfiniteFlightAirportEditing/Navigation/commit/b15db8010e8dd8e62142c7e75d49694416695756

**Comment by ItsW1ll** [comment]
Merged in #772
