### ISSUE TITLE
KOQU

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#757]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169).

ILS equipped:
Runway 16

**Comment by ewanfleming** [comment]
May or may not have fixed this in #764

**Comment by ewanfleming** [comment]
Fixed  in: https://github.com/InfiniteFlightAirportEditing/Navigation/commit/067dfffee76d772998fac6594cc00c335e3a54ed
Thanks for the report!

**Comment by dushyants19** [comment]
@moritzbabl thought i was looking at the airports repo for a sec. Thank god

**Comment by ewanfleming** [comment]
Disappointing I know.

**Comment by ItsW1ll** [comment]
Fixed in 1bd7e49
