### ISSUE TITLE
Brazilian Waypoints

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#781]
this worksheet is official and is available in the Brazilian AIP, it contains all coordinates of the Brazilian waypoints that are in SIDs, STARs, Airways and IACs.

https://www.aisweb.aer.mil.br/download/?public=3d3b37ef-c01b-4d8b-84c3eddb587aa5ec.pdf&p=Fixos_Planilha

updated on 02/01/2018

**Comment by ItsW1ll** [comment]
Wow, 128 pages of waypoints! 

Is there a file we can convert and upload?

**Comment by FellipeEdu** [comment]
convert to the coordinate format used in the IF?

**Comment by FellipeEdu** [comment]
I think unfortunately not :/

**Comment by ThomasR01** [comment]
I can help out with this issue.
