### ISSUE TITLE
EGHH

### ISSUE THREAD

**Issue by ghost** [InfiniteFlightAirportEditing/Navigation#8]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS: (If any)

08/26

# References: (Official sources/charts)

http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=35&Itemid=84.html

**Comment by Swang007** [comment]
@carmichaelalonso recently converted the navigation data to .json format, which makes it MUCH easier to read and understand, which is available here:
https://github.com/InfiniteFlightAirportEditing/Navigation/blob/master/VOR.json

**Comment by Swang007** [comment]
This would be the file where that is found: https://github.com/InfiniteFlightAirportEditing/Navigation/blob/master/DME.dat
However, the code says there should only be one DME:
    "12 39.96057892 -94.92521667     1160    11550   130   0.000  STJ ST JOSEPH VORTAC",
    "12 38.86068726 -90.48236847      450    11740   130   0.000  STL ST LOUIS VORTAC",
    "12 18.03811646 -63.11827850       13    11300   130   0.000  PJM ST MAARTEN VOR-DME",
    "12 27.90776443 -82.68431091        9    11640   130   0.000  PIE ST PETERSBURG VORTAC",
    "12 -21.31641769  55.41716766       52    11590    40   0.000  PRF ST PIERRE PIERREFONDS VOR-DME",
    "12 18.35581970 -65.02455902      679    10860    40   0.000  STT ST THOMAS VOR-DME",

**Comment by carmichaelalonso** [comment]
DMEs were not changed, however I removed duplicates from VORs. I don't think this made its way into the update though.
