### ISSUE TITLE
KHYI

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#809]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

ILS Runway moved

# Runway(s) with ILS (If any)

RWY 13 (Only 13; Reciprocal RWY 31 is not equipped with an ILS system)

# References (Official sources/charts)

https://flightaware.com/resources/airport/HYI/IAP/ILS+OR+LOC+RWY+13/pdf

**Comment by ewanfleming** [comment]
Has this been added to the repo? Was attempting to fix it but if there's no airport, there's no fix, sorry.

**Comment by ItsW1ll** [comment]
Added to the repo now

**Comment by brennanhackard** [comment]
Fixed in #1504
