### ISSUE TITLE
KSAT

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#813]
# Summary of Navigation issue. (ILS, Waypoints, etc.)
I have changed the runway numbers so that it complies with Val's file checker, I think the runway was moved during redo. 

# Runway(s) with ILS (If any)

04,13R,30L

# References (Official sources/charts)

http://www.airnav.com/airport/SAT (Click links at the bottom of the page)

**Comment by ewanfleming** [comment]
Fixed in https://github.com/InfiniteFlightAirportEditing/Navigation/pull/863
