### ISSUE TITLE
EDDR

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#815]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

Runway moved

# Runway(s) with ILS (If any)

26

# References (Official sources/charts)

http://nav.vatsim-germany.org/files/edgg/charts/eddr/public/EDDR_ILS_LOC_RWY27.pdf

**Comment by moritzbabl** [comment]
fixed
