### ISSUE TITLE
LGTS

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#817]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

Runways Moved

# Runway(s) with ILS (If any)

10L,16

# References (Official sources/charts)

http://www.aeolus.gr/pdfs/LGTS_JEP.pdf

**Comment by CptNathanHope** [comment]
Fixed in #925

**Comment by moritzbabl** [comment]
ILS 16 realignment required (new runway ILS not yet available)
https://www.ead.eurocontrol.int/eadbasic/pamslight-16A4900E72F585835F69ABF0631EEA5C/CVMQCRAWTGB4K/EN/Charts/AD/AIRAC/LG_AD_2_LGTS_IAC-2_en_2020-01-02.pdf

**Comment by moritzbabl** [comment]
Now we also have 10-28 ILS Data

https://www.ead.eurocontrol.int/eadbasic/pamslight-B41B2640785E98698D91A34678611931/CVMQCRAWTGB4K/EN/Charts/AD/AIRAC/LG_AD_2_LGTS_IAC-13_en_2020-08-13.pdf

**Comment by Czechoslovaki** [comment]
@moritzbabl just for runway 10?

**Comment by moritzbabl** [comment]
> @moritzbabl just for runway 10?

Apparently, yes. Eurocontrol doesn't show 28 ILS charts
