### ISSUE TITLE
UATT

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#818]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS (If any)

13C,31C

# References (Official sources/charts)

http://vau.aero/navdb/chart/UATT.pdf

**Comment by CptNathanHope** [comment]
Fixed in #926

**Comment by Czechoslovaki** [comment]
Runway with ILSes renamed and elevation changed.
