### ISSUE TITLE
KILG

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#826]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS (If any)

RWY 1

# References (Official sources/charts)

https://download.aopa.org/ustprocs/current/NE-3/ilg_ils_or_loc_rwy_01.pdf?_ga=2.43333093.1710785506.1521302680-740766034.1521302680

**Comment by CptNathanHope** [comment]
Fixed in #927
