### ISSUE TITLE
KOAK

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#828]
# Summary of Navigation issue. (ILS, Waypoints, etc.)

Runway's Changed

# Runway(s) with ILS (If any)

12,30,28R 

# References (Official sources/charts)

http://ww1.jeppesen.com/documents/aviation/notices-alerts/chart-alert/KOAK/KOAKcharts2.pdf

**Comment by CptNathanHope** [comment]
Fixed in #928
