### ISSUE TITLE
SKBG

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#834]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS: (If any)

35

# References: (Official sources/charts)

http://www.aerocivil.gov.co/servicios-a-la-navegacion/servicio-de-informacion-aeronautica-ais/Documents/13%20SKBG.pdf

**Comment by CptNathanHope** [comment]
Fixed in #930

**Comment by MBeringuy** [comment]
I need this problem to be reopened for adjustments.
