### ISSUE TITLE
EKSP

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#835]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway Moved

# Runway(s) with ILS: (If any)

10L,28R

# References: (Official sources/charts)

https://aim.naviair.dk/en/

**Comment by orangejuicie** [comment]
This issue titled "EKSP" but chart is EKSB.
Which is correct?

**Comment by MajorTomMueller** [comment]
uups, let me check

**Comment by MajorTomMueller** [comment]
EKSP Skydstrup is correct, EKSB Sonderborg has no rwy 10L/28R
official charts:
https://aim.naviair.dk/en/

**Comment by CptNathanHope** [comment]
Fixed in #932
