### ISSUE TITLE
KBTL

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#836]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway added

# Runway(s) with ILS: (If any)

23R

# References: (Official sources/charts)

https://www.airnav.com/airport/KBTL

**Comment by CptNathanHope** [comment]
Fixed in #934

**Comment by brunocr98** [comment]
Uhm, this one is a duplicate #691

**Comment by orangejuicie** [comment]
uhoh.
sorry...
