### ISSUE TITLE
LMML

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#838]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runways Moved

# Runway(s) with ILS: (If any)

31,13

# References: (Official sources/charts)

http://www.fly-sea.com/charts/LMML.pdf

**Comment by CptNathanHope** [comment]
Fixed in #937

**Comment by zhf21** [comment]
The runways were moved when MBeringuy reworked the airport in 2019. The fixes are minimal; however, I am bored and noticed that I was ever so slightly off when landing. I would appreciate it if I could make the changes. :)
