### ISSUE TITLE
KASH

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#839]
♻️

**Comment by orangejuicie** [comment]
This ILS might be correct already.

**Comment by CptNathanHope** [comment]
This is a duplicate issue (see #388). The ILS has been fixed and does not require any further changes. Please recycle this as soon as possible. Thanks!

**Comment by CptNathanHope** [comment]
Part of [Project New England](https://community.infinite-flight.com/t/project-new-england/43169/).

_ILS equipped:_ Runway 14
https://flightaware.com/resources/airport/KASH/IAP/ILS+OR+LOC+RWY+14
