### ISSUE TITLE
KYIP

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Navigation#847]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

ILS

# Runway(s) with ILS: (If any)

5R/23L

# References: (Official sources/charts)

http://155.178.201.160/d-tpp/1803/00467IL5R.PDF
http://155.178.201.160/d-tpp/1803/00467IL23L.PDF

**Comment by brennanhackard** [comment]
Fixed in #1504
