### ISSUE TITLE
KMGY

### ISSUE THREAD

**Issue by netjets-1951** [InfiniteFlightAirportEditing/Navigation#848]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Localizer

# Runway(s) with ILS: (If any)

Not an ILS, but has a localizer, Runway 20

# References: (Official sources/charts)

http://155.178.201.160/d-tpp/1803/05042LD20.PDF

**Comment by brennanhackard** [comment]
Fixed in #1504
