### ISSUE TITLE
FGSL

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#852]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway number changed/moved

# Runway(s) with ILS: (If any)

22

# References: (Official sources/charts)

http://www.ais-asecna.org/en/atlas/guineeequ/malabo.htm

**Comment by CptNathanHope** [comment]
Fixed in #942

**Comment by ItsW1ll** [comment]
Runway numbers not changed in LOC.json
