### ISSUE TITLE
HEGN

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#853]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway number changed/moved

# Runway(s) with ILS: (If any)

34R

# References: (Official sources/charts)

http://vau.aero/navdb/chart/HEGN.pdf

**Comment by CptNathanHope** [comment]
Fixed in #944.

**Comment by ItsW1ll** [comment]
Runway numbers not changed!!
