### ISSUE TITLE
KIAD

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#854]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway number changed/moved

# Runway(s) with ILS: (If any)

12,19R,19C,19L,01R,01L.01C

# References: (Official sources/charts)

http://www.fly-sea.com/charts/KIAD.pdf

**Comment by CptNathanHope** [comment]
Originally completed by @williamqarmstrong in #875. 
Small correction made by me in [`e4dff6b`](https://github.com/InfiniteFlightAirportEditing/Navigation/commit/e4dff6b4ca84c32d912c1d1b080aae9c0e517fd3).
