### ISSUE TITLE
OEPS

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#859]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway added and moved.

# Runway(s) with ILS: (If any)

35R,35L,17L

# References: (Official sources/charts)

http://www.sa-ivao.net/charts_file/chart-OEPS.pdf

**Comment by CptNathanHope** [comment]
Link above is no longer working. 

New ref: https://gaca.gov.sa/gaca/AIB/2018-01-01/html/eAIP/OE-AD-2.OEPS-en-SA.html
