### ISSUE TITLE
Missing waypoints in London region

### ISSUE THREAD

**Issue by Will171** [InfiniteFlightAirportEditing/Navigation#86]
SPEAR - 513434N 0004201E
![image](https://cloud.githubusercontent.com/assets/16463484/14962455/beaf315e-1096-11e6-82f0-7fdf815ed67a.png)

NILON - Lat 51.35'46.00"N
              Long 0.38'4.00" E
(Waypoint exsists but not used that often)
![image](https://cloud.githubusercontent.com/assets/16463484/14962678/fdd9af48-1097-11e6-917b-d13f2c43375b.png)
![image](https://cloud.githubusercontent.com/assets/16463484/14962679/fdfa070c-1097-11e6-89b3-7abe6095dd7e.jpeg)

**Comment by henrikbg** [comment]
Updated via 4a799bd.
