### ISSUE TITLE
KGSO

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Navigation#865]
**Summary of Navigation issue: (ILS, Waypoints, etc.)**
ILS
Runway was moved(?)
**Runway(s) with ILS:**
<05R/L; 23R/L; 32>

**source:**
< https://de.flightaware.com/resources/airport/KGSO/IAP/ILS+Y+OR+LOC_DME+Y+RWY+32>

**Comment by johanneskkl** [comment]
wait. It hasn´t been added to the repo yet. Sorry, my fault

**Comment by ItsW1ll** [comment]
Okay no probs. Please comment below when it is added!

**Comment by johanneskkl** [comment]
Has been added
