### ISSUE TITLE
LJMB

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#869]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

runway moved

# Runway(s) with ILS: (If any)

32

# References: (Official sources/charts)

https://www.sloveniacontrol.si/acrobat/aip/Operations/2013-06-11/pdf/LJ-AD-2.LJMB-en-GB.pdf

**Comment by CptNathanHope** [comment]
Fixed in #957
