### ISSUE TITLE
SKRG

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#872]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved/runways changed

# Runway(s) with ILS: (If any)

01

# References: (Official sources/charts)

http://ww1.jeppesen.com/documents/aviation/notices-alerts/hubwatch/SKRG/SKRG.pdf

**Comment by ItsW1ll** [comment]
01 needs to be changed to 1

**Comment by orangejuicie** [comment]
I fixed back to 01.
