### ISSUE TITLE
WSAC

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#88]
Runways changed to 02R/20L

**Comment by DavidCutler** [comment]
Since this is a military base, I can't seem to find any ILS or approach charts in general. Could you check Navigraph?

**Comment by Swang007** [comment]
@kilt46 Did you change runway locations as well or just the numbers?

**Comment by kilt46** [comment]
Just the numbers

**Comment by henrikbg** [comment]
I don't think this airport has an ILS approach. There's nothing in the files regarding WSAC.

**Comment by AleksanderIF** [comment]
https://aim-sg.caas.gov.sg/aip/2020-11-12/final/2020-11-12/html/index-en-GB.html

**Comment by AleksanderIF** [comment]
Rwy 02R/20L - ILS https://aim-sg.caas.gov.sg/aip/2020-11-12/final/2020-11-05-Non-AIRAC/html/eAIP/AD-2.WSSS-en-GB.html?s=E1195041A282E8258A801EEA64232CB9831EBB4F#AD-2.WSSS.19
