### ISSUE TITLE
SBBR

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#894]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< ILS >

# Runway(s) with ILS: (If any)

< all, however 11R-29L are without in IF >

# References: (Official sources/charts)

< 11R: https://www.aisweb.aer.mil.br/download/?arquivo=84313e46-ae93-1033-a49b-72567f175e3a
    29L: https://www.aisweb.aer.mil.br/download/?arquivo=7e7d5a90-eb31-1033-a49b-72567f175e3a >

**Comment by FellipeEdu** [comment]
chart 29L link fixed

**Comment by MBeringuy** [comment]
Can you please do this? Thanks.

**Comment by zhf21** [comment]
Removal of RWY 29R ILS + minor fixes.

<img width="1440" alt="Screen Shot 2021-09-27 at 8 15 09 PM" src="https://user-images.githubusercontent.com/67797012/135002044-6f842e37-8485-4d4a-9131-e5e88157c0ec.png">
