### ISSUE TITLE
EGTC STAR's and SID's

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#896]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

RNAV APPR
DEKAP : 515637.28N 0005337.10W
DOTIT : 515304.01N 0005238.49W
TC03I : 515537.23N 0004542.18W
TC03F : 515825.61N 0004254.33W
RW03 : 520400.47N 0003719.28W
 NDB: wco 515111N 0005745W
ADSON : 521708.47N 0003304.51W
BAPIS : 521818.22N 0002253.23W
BEVLU : 521211.16N 0002005.53W
TC21I : 521312.96N 0002802.74W
TC21F : 521018.34N 0003059.14W
RW21 : 520444.32N 0003635.27W

# References: (Official sources/charts)

http://www.nats-uk.ead-it.com/public/index.php%3Foption=com_content&task=blogcategory&id=48&Itemid=97.html

**Comment by ThomasR01** [comment]
Added these in 7bca237
