### ISSUE TITLE
KFXE-Fort Lauderdale Executive Airport-Florida-USA

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#897]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Enter text here >

# Runway(s) with ILS: (If any)

Runway 08/26 renamed to 09/27 as per latest charts

# References: (Official sources/charts)

Navigraph/Jepessen

**Comment by danisrils39** [comment]
ILS needs an updating, elevation was changed 

[05942IL9.PDF](https://github.com/InfiniteFlightAirportEditing/Navigation/files/2917650/05942IL9.PDF)
