### ISSUE TITLE
KSJC

### ISSUE THREAD

**Issue by kilt46** [InfiniteFlightAirportEditing/Navigation#898]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Enter text here >

# Runway(s) with ILS: (If any)

Renumbered Runways 18/36 and 06/24

# References: (Official sources/charts)

Navigraph / Jepessen

**Comment by orangejuicie** [comment]
I can't find ILS chart on this airport.
May be this airport has no ILS approach.

**Comment by ItsW1ll** [comment]
I will double check..

**Comment by MajorTomMueller** [comment]
All Instrument approaches are GPS based.
https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/results/?cycle=1806&ident=KSPG

**Comment by ItsW1ll** [comment]
You are correct.

Can we recycle?

**Comment by brunocr98** [comment]
Since this is sort of invalid, then can this issue be recycled into KSJC? I'll be fixing the airport in the following days. Runway 12R/30L has ILS. I'll notify you when it's finished and uploaded.

http://www.airnav.com/airport/KSJC

**Comment by CptNathanHope** [comment]
♻️

**Comment by brunocr98** [comment]
Airport uploaded; you can now go ahead.

**Comment by CptNathanHope** [comment]
Fixed in #966
