### ISSUE TITLE
KSFO

### ISSUE THREAD

**Issue by Swang007** [InfiniteFlightAirportEditing/Navigation#9]
https://community.infinite-flight.com/t/wrong-indicated-ils-heading-at-ksfo/8409/4

**Comment by Swang007** [comment]
@carmichaelalonso

**Comment by HenrikBerg02** [comment]
![screen shot 2016-02-03 at 11 00 43 pm](https://cloud.githubusercontent.com/assets/14116830/12806261/09a63c92-caca-11e5-9d86-ca13682e8206.png)

According to the image, it says the bearing is around 298 which is way off... This is strange.

**Comment by moritzbabl** [comment]
Moved the runway during editing, maybe the fix helps with removing the ILS issue

**Comment by moritzbabl** [comment]
Since we have a cleaned file now, maybe we can finally get this ILS to work

**Comment by ItsW1ll** [comment]
Would you like me to do it then?

**Comment by moritzbabl** [comment]
As you wish, I’ll have to get back into this anyway I guess

**Comment by ItsW1ll** [comment]
This may have fixed it.. we shall see

**Comment by brennanhackard** [comment]
Runways were slightly moved.
