### ISSUE TITLE
KACV

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#902]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Moved ILS Runway 

# Runway(s) with ILS: (If any)

RWY 32

# References: (Official sources/charts)

https://flightaware.com/resources/airport/ACV/IAP/ILS++OR+LOC+RWY+32/pdf

**Comment by brennanhackard** [comment]
Fixed in #1504
