### ISSUE TITLE
KBTR

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#936]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Moved Runways 04L/22R and 13/31

# Runway(s) with ILS: (If any)

ILS RWY 13, 22R.

Other RWY's are either VOR or RNAV approaches

# References: (Official sources/charts)

13: https://flightaware.com/resources/airport/BTR/IAP/ILS+OR+LOC+RWY+13/pdf
22R: https://flightaware.com/resources/airport/BTR/IAP/ILS+OR+LOC_DME+RWY+22R/pdf

**Comment by CptNathanHope** [comment]
Fixed in #940 by @ewanfleming
