### ISSUE TITLE
Moved ESGP runways.

### ISSUE THREAD

**Issue by samuelandersson** [InfiniteFlightAirportEditing/Navigation#94]
AFAIK 19 or 01 has ILS, but not the one that cuts through 19/01.

Moved both either way.

**Comment by DavidCutler** [comment]
You sure this one has an ILS approach? Can't find any charts or information on it.

**Comment by Swang007** [comment]
I think it's runway 19, because it shows up in both nav files. Fixed 19, 01 should fix itself with the automatically generated GPS approach.
