### ISSUE TITLE
KSAV

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#948]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

RWY 1/19 created and RWY 28/10 moved

# Runway(s) with ILS: (If any)

RWY 1 and RWY 10

# References: (Official sources/charts)

RWY 1: https://flightaware.com/resources/airport/SAV/IAP/ILS+OR+LOC+RWY+01/pdf
RWY 10: https://flightaware.com/resources/airport/SAV/IAP/ILS+OR+LOC+RWY+10/pdf

**Comment by ItsW1ll** [comment]
Re opened as 01 needs to be changed to just 1
