### ISSUE TITLE
LFBE

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#959]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runways moved/renumbered

# Runway(s) with ILS: (If any)

Now 09/27

# References: (Official sources/charts)

http://vau.aero/navdb/chart/LFBD.pdf

**Comment by orangejuicie** [comment]
Chart shows LFBD. According to rwy number it might LFBE.
Which is correct?

**Comment by MajorTomMueller** [comment]
Official France authoritie:
LFBE:
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_26_APR_2018/FRANCE/AIRAC-2018-04-26/pdf/FR-AD-2.LFBE-fr-FR.pdf
LFBD:
https://www.sia.aviation-civile.gouv.fr/dvd/eAIP_26_APR_2018/FRANCE/AIRAC-2018-04-26/pdf/FR-AD-2.LFBD-fr-FR.pdf

But I have to admit that I haven’t understood the question....

**Comment by ItsW1ll** [comment]
Oops attached wrong charts thanks Tom for correcting!!

**Comment by orangejuicie** [comment]
Okay.I'll do this.
Thanks.
