### ISSUE TITLE
WSSS

### ISSUE THREAD

**Issue by NatIsrael972** [InfiniteFlightAirportEditing/Navigation#96]
**02L/20R**
Edge Lights: MIRL > HIRL
Markings 2 (20R): Precision (US) > Non-Precision (US)
Approach Lights 2 (20R): ALSF-II > ALSF-I
PAPI (Right) added

**02C/20C**
Edge Lights: MIRL > HIRL
Markings 1 (02C): Precision (US) > Non-Precision (US)
Approach Lights 2 (02C): ALSF-II > ALSF-I
PAPI (Right) added

---

Original WSSS BCN renamed as CABW BCN, coordinates are that of Changi Air Base West (CABW)'s BCN.

New BCN named WSSS BCN located off fuel farm in the north added

Windsocks moved but as it is not important, no further information will be provided.

**Comment by henrikbg** [comment]
This is not a valid navigation issue.
