### ISSUE TITLE
KFAT

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#963]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runways 11L/29R and 11R/29L moved

# Runway(s) with ILS: (If any)

RWY 29R

# References: (Official sources/charts)

29R: https://flightaware.com/resources/airport/FAT/IAP/ILS+Y+OR+LOC+Y+RWY+29R/pdf

**Comment by brennanhackard** [comment]
Fixed :D

**Comment by brennanhackard** [comment]
Fixed :D
