### ISSUE TITLE
KTYS

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#967]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

RWY's 05L/23R and 05R/23L moved

# Runway(s) with ILS: (If any)

05L, 23L and 23R

# References: (Official sources/charts)

05L: https://flightaware.com/resources/airport/TYS/IAP/ILS+OR+LOC+RWY+05L/pdf
23L: https://flightaware.com/resources/airport/TYS/IAP/ILS+OR+LOC+RWY+23L/pdf
23R: https://flightaware.com/resources/airport/TYS/IAP/ILS+OR+LOC+RWY+23R/pdf

**Comment by brennanhackard** [comment]
Fixed in #1504
