### ISSUE TITLE
Suriname Waypoints 

### ISSUE THREAD

**Issue by sudafly** [InfiniteFlightAirportEditing/Navigation#97]
Suriname need Waypoints: http://opennav.com/waypoint/SR
![image](https://cloud.githubusercontent.com/assets/17830984/15454627/c049663a-203e-11e6-9188-7429e38f8a53.png)

**Comment by Swang007** [comment]
Is this actually an issue? All these fixes already exist in the Fixes file. The coordinates aren't exactly the same but pretty similar I'd say.
