### ISSUE TITLE
KDRO 

### ISSUE THREAD

**Issue by CptNathanHope** [InfiniteFlightAirportEditing/Navigation#974]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved/changed.

# Runway(s) with ILS: (If any)

03

# References: (Official sources/charts)

https://flightaware.com/resources/airport/KDRO/IAP/ILS+OR+LOC_DME+RWY+03

**Comment by ItsW1ll** [comment]
03 needs to be change to 3
