### ISSUE TITLE
KPUB (ILS 08R)

### ISSUE THREAD

**Issue by AxelBeder** [InfiniteFlightAirportEditing/Navigation#98]
The GS isn't correctly set.There GS angle should be 3.00 instead of 4/5.

<img width="596" alt="capture d ecran 2016-05-29 a 16 57 47" src="https://cloud.githubusercontent.com/assets/11073474/15634206/83381266-25be-11e6-95e9-dd2a4fbb39bb.png">

**Comment by henrikbg** [comment]
Fixed via 94998e3.

**Comment by RyanEpps** [comment]
Is attached to 8L/26R and needs changed to 8R/26L

**Comment by MajorTomMueller** [comment]
solved

**Comment by MajorTomMueller** [comment]
#1927
