### ISSUE TITLE
LIRE

### ISSUE THREAD

**Issue by johanneskkl** [InfiniteFlightAirportEditing/Navigation#986]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

The runway has ILS and has been closed and completely removed from the airport file.

# Runway(s) with ILS: (If any)

Runway 13/31 
 
# References: (Official sources/charts)

http://worldaerodata.com/wad.cgi?id=IT49301&sch=LIRE

**Comment by MajorTomMueller** [comment]
ENAV, Italy official AIP
https://www.enav.it/enavWebPortalStatic/AIP/AIP/ad/ad2/ADPRA1-1.pdf

**Comment by MajorTomMueller** [comment]
[ADPRA2-1.pdf](https://github.com/InfiniteFlightAirportEditing/Navigation/files/2080027/ADPRA2-1.pdf)
