### ISSUE TITLE
London City (EGLC) 

### ISSUE THREAD

**Issue by ItsW1ll** [InfiniteFlightAirportEditing/Navigation#99]
Runway was moved to fit the wed imagery.
Also the heading was changed :)

**Comment by henrikbg** [comment]
Has this been committed to the airports repository?

**Comment by Will171** [comment]
henrik, the newest 1 I sent to you yesterday had the ruway heading changed and it was moved to fit the wed imagery

**Comment by ItsW1ll** [comment]
Runway was moved.

**Comment by ItsW1ll** [comment]
Committed to f521b74

**Comment by ItsW1ll** [comment]
Runway tweaked in latest version.

**Comment by ItsW1ll** [comment]
Merged.
