### ISSUE TITLE
KRAP

### ISSUE THREAD

**Issue by Aviationluver** [InfiniteFlightAirportEditing/Navigation#993]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

RWY's 14/32 and 5/23 moved

# Runway(s) with ILS: (If any)

RWY 32 (14 is RNAV)

# References: (Official sources/charts)

https://flightaware.com/resources/airport/RAP/IAP/ILS+OR+LOC+RWY+32/pdf

**Comment by brennanhackard** [comment]
Fixed in #1504
