### ISSUE TITLE
KBMG

### ISSUE THREAD

**Issue by RyanEpps** [InfiniteFlightAirportEditing/Navigation#994]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

Runway moved/changed.

# Runway(s) with ILS: (If any)

35

# References: (Official sources/charts)

https://flightaware.com/resources/airport/KBMG/IAP/ILS+OR+LOC_DME+RWY+35

**Comment by brennanhackard** [comment]
Fixed in #1504
