### ISSUE TITLE
SBJV

### ISSUE THREAD

**Issue by FellipeEdu** [InfiniteFlightAirportEditing/Navigation#995]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< runway length changed for 1640m because DT in RWY 15 >

# Runway(s) with ILS: (If any)

< RWY 33 >

# References: (Official sources/charts)

< https://www.aisweb.aer.mil.br/download/?arquivo=5170eb6b-98e7-427d-86a24f2c840d8927 >

**Comment by moritzbabl** [comment]
http://ais.decea.gov.br/download/?arquivo=5170eb6b-98e7-427d-86a24f2c840d8927&apikey=1587263166

Airport updated

**Comment by zhf21** [comment]
LOC -> ILS-Cat-I.

<img width="401" alt="Screen Shot 2021-09-27 at 9 52 10 PM" src="https://user-images.githubusercontent.com/67797012/135009293-aef0f836-ad20-4204-b8f2-1d3b8926d0b3.png">
