### ISSUE TITLE
SBKG

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#998]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Airport redone from scratch >

# Runway(s) with ILS: (If any)

< Runway 15 >

# References: (Official sources/charts)

< https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjCkaPXk-XbAhXGh5AKHUioC1YQFggoMAA&url=https%3A%2F%2Fwww.aisweb.aer.mil.br%2Fdownload%2F%3Farquivo%3D76e0da9c-f5e6-1031-95e7-72567f175e3a&usg=AOvVaw1ndwuiGl97Ygn4JdqYpfur >

**Comment by zhf21** [comment]
ILS-Cat-I -> LOC. 

<img width="406" alt="Screen Shot 2021-09-27 at 9 49 10 PM" src="https://user-images.githubusercontent.com/67797012/135009068-fed24516-27f8-4602-9314-3f6408e22fc5.png">
