### ISSUE TITLE
SBSL

### ISSUE THREAD

**Issue by MBeringuy** [InfiniteFlightAirportEditing/Navigation#999]
# Summary of Navigation issue: (ILS, Waypoints, etc.)

< Airport redone from scratch >

# Runway(s) with ILS: (If any)

< Runway 06 >

# References: (Official sources/charts)

< https://www.aisweb.aer.mil.br/download/?arquivo=808c44aa-cb6a-1032-8701-72567f175e3a >

**Comment by FellipeEdu** [comment]
Can anyone do this, please?
